name: flutterware
description: 'A collection of GUI tools to help Flutter development. This is a complement to your IDE with Flutter specific needs.'
version: 0.2.0 # Keep it sync with flutterware_app
homepage: https://github.com/xvrh/flutterware

environment:
  sdk: '^3.1.0'
  flutter: '>=3.13.0'

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.3.0
  collection: ^1.16.0
  crypto: ^3.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  logging: ^1.0.0
  meta: ^1.7.0
  package_config: ^2.0.0
  path: ^1.8.0
  pool: ^1.5.0
  stream_channel: ^2.1.0
  test_api: ^0.6.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  analyzer:
  build_runner:
  built_value_generator:
  dart_style:
  json_serializable:
  lints:
  process_runner:
  vendor:
  yaml: