name: flutter_studio
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  args:
  built_collection:
  built_value:
  collection:
  flutter_test:
    sdk: flutter
  path:
  stream_channel:
  test:
  process_runner:

dev_dependencies:
  build_runner:
  built_value_generator:
  json_serializable:
  lints:
