// The generated half: one arguments class per declared widget, one per scene
// class, and the tracks class that makes a motion typed.
//
// This is where every string in the system that is not in a declaration
// ends up, and nobody types any of them. A scene file writes
// `ExternalNode(const DrinkBadgeArgs(size: 140))` and a motion writes
// `args: DrinkBadgeTracks(size: …)`; both are ordinary Dart the compiler
// checks, and an argument the widget does not declare cannot be spelled.
//
// Only `double` and `SceneColor` arguments get a track slot. A label has no
// in-between values, so animating it is not a refusal here but a name that
// does not exist.
//
// The package's tokens get a class too — `SceneTokens`, a const with one
// typed field per declared token and the declared value as its default —
// so `tokens.brand` in a scene file is a field the compiler checks, and a
// token nobody declared is a name that does not exist.
import 'package:dart_style/dart_style.dart';
import 'package:flutterware/scene_authoring.dart';

import 'externals_file.dart';
import 'tokens_file.dart';

/// One scene class the generator writes arguments for, and where it lives
/// relative to the generated file.
class SceneClassDecl {
  SceneClassDecl(this.className, this.params, this.importPath);

  final String className;
  final List<SceneParamDecl> params;

  /// The scene file, relative to the generated file's directory.
  final String importPath;
}

const _header = '''
// GENERATED by the flutterware scene editor. Do not edit.
//
// One arguments class per widget the app declares and per scene class
// beside it, so a scene file and a motion can name arguments with types
// instead of strings. Regenerated whenever a declaration or a scene's
// parameters change; every edit here is lost on the next save.
''';

/// The generated file's whole source.
String emitSceneArgs({
  required List<ExternalWidgetDecl> externals,
  required List<SceneClassDecl> scenes,
  List<SceneTokenDecl> tokens = const [],
  String? externalsImport,
}) {
  var out = StringBuffer(_header)
    ..writeln()
    ..writeln("import 'package:flutterware/scene_authoring.dart';");
  var imports = [
    if (externalsImport != null && externals.isNotEmpty) externalsImport,
    for (var s in scenes) s.importPath,
  ]..sort();
  if (imports.isNotEmpty) out.writeln();
  for (var i in imports) {
    out.writeln("import '$i';");
  }

  for (var w in externals) {
    _argsClass(
      out,
      entry: w.entry,
      base: 'SceneExtArgs',
      fields: [
        for (var a in w.args)
          (name: a.name, type: a.typeName, fallback: a.defaultSource),
      ],
      build:
          '  @override\n'
          '  Object build() =>\n'
          "      _external('${w.entry}').build(SceneArgs(toMap()));\n",
    );
  }
  for (var s in scenes) {
    var fields = [
      for (var p in s.params)
        if (p.kind != SceneParamKind.list)
          (name: p.name, type: p.typeName, fallback: _literal(p.defaultValue)),
    ];
    _argsClass(
      out,
      entry: s.className,
      base: 'SceneRefArgs',
      fields: fields,
      build:
          '  @override\n'
          '  SceneDefinition build() => ${s.className}('
          '${[for (var f in fields) '${f.name}: ${f.name}'].join(', ')});\n',
    );
  }

  if (tokens.isNotEmpty) _tokensClass(out, tokens);

  if (externals.isNotEmpty) {
    out
      ..writeln()
      ..writeln('/// The declaration an arguments class was generated from —')
      ..writeln('/// how a node builds itself, and why a shipped app hands')
      ..writeln('/// the view nothing.')
      ..writeln('ExternalWidget _external(String entry) =>')
      ..writeln(
        '    $sceneExternalsSymbol.firstWhere((w) => w.entry == entry);',
      );
  }
  return _formatter.format(out.toString());
}

typedef _Field = ({String name, String type, String? fallback});

void _argsClass(
  StringBuffer out, {
  required String entry,
  required String base,
  required List<_Field> fields,
  required String build,
}) {
  var name = '${entry}Args';
  out
    ..writeln()
    ..writeln('class $name extends $base {')
    ..writeln('  const $name(${_formals(fields)});')
    ..writeln();
  for (var f in fields) {
    out.writeln('  final ${f.type}${f.fallback == null ? '?' : ''} ${f.name};');
  }
  out
    ..writeln()
    ..writeln('  @override')
    ..writeln("  String get entry => '$entry';")
    ..writeln()
    ..writeln('  @override')
    ..writeln('  $name merge(SceneArgs fx) => $name(')
    ..writeln(
      [
        for (var f in fields)
          "        ${f.name}: fx.${_reader(f.type)}('${f.name}') ?? ${f.name},",
      ].join('\n'),
    )
    ..writeln('      );')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Map<String, Object?> toMap() => {')
    ..writeln(
      [
        for (var f in fields)
          f.fallback == null
              ? "        '${f.name}': ?${f.name},"
              : "        '${f.name}': ${f.name},",
      ].join('\n'),
    )
    ..writeln('      };')
    ..writeln()
    ..write(build)
    ..writeln('}');

  var tracks = [
    for (var f in fields)
      if (_animatable(f.type)) f,
  ];
  out
    ..writeln()
    ..writeln('class ${entry}Tracks extends SceneExtTracks {')
    ..writeln('  const ${entry}Tracks(${_formals(tracks, defaults: false)});')
    ..writeln();
  for (var f in tracks) {
    out.writeln('  final MotionTrack? ${f.name};');
  }
  out
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Map<String, MotionTrack> toMap() => {')
    ..writeln(
      [for (var f in tracks) "        '${f.name}': ?${f.name},"].join('\n'),
    )
    ..writeln('      };')
    ..writeln('}');
}

/// `class SceneTokens { const SceneTokens({this.brand = const SceneColor(…)
/// …}); final SceneColor brand; … }` — the declared set as a const, so a
/// scene's formal can default to it, and another set (a mode) is the same
/// class with other arguments.
void _tokensClass(StringBuffer out, List<SceneTokenDecl> tokens) {
  out
    ..writeln()
    ..writeln('/// The tokens `$sceneTokensFileName` declares, typed. A scene')
    ..writeln(
      '/// reads them through its tokens formal — `fill: tokens.brand`;',
    )
    ..writeln('/// the bare constructor is the declared set.')
    ..writeln('class $sceneTokensClassName {')
    ..writeln(
      '  const $sceneTokensClassName({${[for (var t in tokens) 'this.${t.name} = ${_literal(t.value)}'].join(', ')}});',
    )
    ..writeln();
  for (var t in tokens) {
    out.writeln('  final ${t.typeName} ${t.name};');
  }
  out.writeln('}');
}

/// A class with no arguments takes no braces — `const OhohArgs()`, not
/// `const OhohArgs({})`, which is not Dart.
String _formals(List<_Field> fields, {bool defaults = true}) => fields.isEmpty
    ? ''
    : '{${[for (var f in fields) 'this.${f.name}${defaults && f.fallback != null ? ' = ${f.fallback}' : ''}'].join(', ')}}';

/// Which [SceneArgs] reader answers for a type — the four kinds an argument
/// may take, and the whole of what a declaration has to say about one.
String _reader(String type) => switch (type) {
  'String' => 'text',
  'bool' => 'flag',
  'SceneColor' => 'color',
  _ => 'number',
};

/// A track interpolates, so only what has in-between values gets a slot.
bool _animatable(String type) => type == 'double' || type == 'SceneColor';

String _literal(Object value) => switch (value) {
  String s => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'",
  SceneColor c =>
    'const SceneColor(0x${c.argb.toRadixString(16).toUpperCase().padLeft(8, '0')})',
  num n => n == n.roundToDouble() ? '${n.toInt()}.0' : '$n',
  _ => '$value',
};

final _formatter = DartFormatter(
  languageVersion: DartFormatter.latestLanguageVersion,
);
