// The generated half: one arguments class per declared widget, one per scene
// class, and the tracks class that makes a motion typed.
//
// This is where every string in the system that is not in a declaration
// ends up, and nobody types any of them. A scene file writes
// `ExternalNode(const DrinkBadgeArgs(size: 140))` and a motion writes
// `args: DrinkBadgeTracks(size: …)`; both are ordinary Dart the compiler
// checks, and an argument the widget does not declare cannot be spelled.
//
// Only `double` and `SceneColor` arguments get a track slot. A label has no
// in-between values, so animating it is not a refusal here but a name that
// does not exist.
//
// The package's tokens get a class too — `SceneTokens`, a const with one
// typed field per declared token and the declared value as its default —
// so `tokens.brand` in a scene file is a field the compiler checks, and a
// token nobody declared is a name that does not exist.
import 'package:dart_style/dart_style.dart';
import 'package:flutterware/scene_authoring.dart';

import 'externals_file.dart';
import 'tokens_file.dart';

/// One scene class the generator writes arguments for, and where it lives
/// relative to the generated file.
class SceneClassDecl {
  SceneClassDecl(this.className, this.params, this.importPath);

  final String className;
  final List<SceneParamDecl> params;

  /// The scene file, relative to the generated file's directory.
  final String importPath;
}

const _header = '''
// GENERATED by the flutterware scene editor. Do not edit.
//
// One arguments class per widget the app declares and per scene class
// beside it, so a scene file and a motion can name arguments with types
// instead of strings. Regenerated whenever a declaration or a scene's
// parameters change; every edit here is lost on the next save.
''';

/// The generated file's whole source.
String emitSceneArgs({
  required List<ExternalWidgetDecl> externals,
  required List<SceneClassDecl> scenes,
  List<SceneTokenDecl> tokens = const [],
  String? externalsImport,
  String? tokensImport,
  List<String> declarationImports = const [],
}) {
  var hasOpaqueTokens = tokens.any((t) => t.isOpaque);
  var out = StringBuffer(_header)
    ..writeln()
    ..writeln("import 'package:flutterware/scene_authoring.dart';");
  // The declaration files' own imports come along, because an opaque type —
  // `ButtonStyle`, `app.Thing` — is spelled here exactly as it was spelled
  // there. Only the ones something spelled here needs: an import nothing
  // uses is a warning in a file nobody edits.
  var opaqueTypes = {
    for (var t in tokens)
      if (t.isOpaque) t.type,
    for (var w in externals)
      for (var a in w.args)
        if (!isValueArgType(a.typeName)) a.typeName,
  };
  var needed = _neededImports(declarationImports, opaqueTypes);
  var packages = [
    for (var i in needed)
      if (i.contains("'package:")) i,
  ]..sort();
  for (var i in packages) {
    out.writeln(i);
  }
  var relative = <String, String>{
    for (var i in needed)
      if (!i.contains("'package:")) _importPath(i): i,
  };
  var imports = {
    if (externalsImport != null && externals.isNotEmpty) externalsImport,
    if (tokensImport != null && hasOpaqueTokens) tokensImport,
    for (var s in scenes) s.importPath,
    ...relative.keys,
  }.toList()..sort();
  if (imports.isNotEmpty) out.writeln();
  for (var i in imports) {
    out.writeln(relative[i] ?? "import '$i';");
  }

  for (var w in externals) {
    _argsClass(
      out,
      entry: w.entry,
      base: 'SceneExtArgs',
      fields: [
        for (var a in w.args)
          (
            name: a.name,
            type: a.typeName,
            fallback: a.defaultSource,
            opaque: !isValueArgType(a.typeName),
          ),
      ],
      build:
          '  @override\n'
          '  Object build() =>\n'
          "      _external('${w.entry}').build(SceneArgs(toMap()));\n",
    );
  }
  for (var s in scenes) {
    var fields = [
      for (var p in s.params)
        if (p.kind != SceneParamKind.list)
          (
            name: p.name,
            type: p.typeName,
            fallback: _literal(p.defaultValue),
            opaque: false,
          ),
    ];
    _argsClass(
      out,
      entry: s.className,
      base: 'SceneRefArgs',
      fields: fields,
      build:
          '  @override\n'
          '  SceneDefinition build() => ${s.className}('
          '${[for (var f in fields) '${f.name}: ${f.name}'].join(', ')});\n',
    );
  }

  if (tokens.isNotEmpty) _tokensClass(out, tokens);

  if (externals.isNotEmpty) {
    out
      ..writeln()
      ..writeln('/// The declaration an arguments class was generated from —')
      ..writeln('/// how a node builds itself, and why a shipped app hands')
      ..writeln('/// the view nothing.')
      ..writeln('ExternalWidget _external(String entry) =>')
      ..writeln(
        '    $sceneExternalsSymbol.firstWhere((w) => w.entry == entry);',
      );
  }
  return _formatter.format(out.toString());
}

typedef _Field = ({String name, String type, String? fallback, bool opaque});

void _argsClass(
  StringBuffer out, {
  required String entry,
  required String base,
  required List<_Field> fields,
  required String build,
}) {
  var name = '${entry}Args';
  out
    ..writeln()
    ..writeln('class $name extends $base {')
    ..writeln('  const $name(${_formals(fields)});')
    ..writeln();
  for (var f in fields) {
    out.writeln('  final ${f.type}${f.fallback == null ? '?' : ''} ${f.name};');
  }
  out
    ..writeln()
    ..writeln('  @override')
    ..writeln("  String get entry => '$entry';")
    ..writeln()
    ..writeln('  @override')
    ..writeln('  $name merge(SceneArgs fx) => $name(')
    ..writeln(
      [
        for (var f in fields)
          f.opaque
              // No fx reader: an object has no in-between values, and a
              // track cannot name it.
              ? '        ${f.name}: ${f.name},'
              : "        ${f.name}: fx.${_reader(f.type)}('${f.name}') ?? ${f.name},",
      ].join('\n'),
    )
    ..writeln('      );')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Map<String, Object?> toMap() => {')
    ..writeln(
      [
        for (var f in fields)
          f.fallback == null
              ? "        '${f.name}': ?${f.name},"
              : "        '${f.name}': ${f.name},",
      ].join('\n'),
    )
    ..writeln('      };')
    ..writeln()
    ..write(build)
    ..writeln('}');

  var tracks = [
    for (var f in fields)
      if (_animatable(f.type)) f,
  ];
  out
    ..writeln()
    ..writeln('class ${entry}Tracks extends SceneExtTracks {')
    ..writeln('  const ${entry}Tracks(${_formals(tracks, defaults: false)});')
    ..writeln();
  for (var f in tracks) {
    out.writeln('  final MotionTrack? ${f.name};');
  }
  out
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Map<String, MotionTrack> toMap() => {')
    ..writeln(
      [for (var f in tracks) "        '${f.name}': ?${f.name},"].join('\n'),
    )
    ..writeln('      };')
    ..writeln('}');
}

/// `class SceneTokens { const SceneTokens({this.brand = const SceneColor(…)
/// …}); final SceneColor brand; … }` — the declared set as a const, so a
/// scene's formal can default to it, and another set (a mode) is the same
/// class with other arguments.
///
/// An opaque token is a getter, not a field: its value is the app's object,
/// which a const cannot hold and this file cannot spell, so it is read from
/// the declaration list at the moment a scene asks — the same move as
/// `_external` below.
void _tokensClass(StringBuffer out, List<SceneTokenDecl> tokens) {
  var values = [
    for (var t in tokens)
      if (!t.isOpaque) t,
  ];
  var opaque = [
    for (var t in tokens)
      if (t.isOpaque) t,
  ];
  var formals = values.isEmpty
      ? ''
      : '{${[for (var t in values) 'this.${t.name} = ${_literal(t.value!)}'].join(', ')}}';
  out
    ..writeln()
    ..writeln('/// The tokens `$sceneTokensFileName` declares, typed. A scene')
    ..writeln(
      '/// reads them through its tokens formal — `fill: tokens.brand`;',
    )
    ..writeln('/// the bare constructor is the declared set.')
    ..writeln('class $sceneTokensClassName {')
    ..writeln('  const $sceneTokensClassName($formals);')
    ..writeln();
  for (var t in values) {
    out.writeln('  final ${t.typeName} ${t.name};');
  }
  // One static set per mode name any token carries: the mode's value where
  // the token names it, the default everywhere else. `modes` is the switch
  // a canvas or an app flips.
  var modeNames = {for (var t in values) ...t.modes.keys}.toList()..sort();
  for (var mode in modeNames) {
    // Inside a const set, so a colour is spelled without its own `const`.
    var args = [
      for (var t in values)
        if (t.modes.containsKey(mode))
          '${t.name}: ${_literal(t.modes[mode]!).replaceFirst('const ', '')}',
    ];
    out
      ..writeln()
      ..writeln(
        '  static const $mode = $sceneTokensClassName(${args.join(', ')});',
      );
  }
  if (modeNames.isNotEmpty) {
    out
      ..writeln()
      ..writeln('  /// Every mode the declaration names, by name.')
      ..writeln(
        '  static const modes = <String, $sceneTokensClassName>{${[for (var m in modeNames) "'$m': $m"].join(', ')}};',
      );
  }
  for (var t in opaque) {
    out
      ..writeln()
      ..writeln("  /// The app's own, as `$sceneTokensFileName` declares it.")
      ..writeln(
        "  ${t.typeName} get ${t.name} => _token('${t.name}')! as ${t.typeName};",
      );
  }
  if (opaque.isNotEmpty) {
    out
      ..writeln()
      ..writeln('  static Object? _token(String name) =>')
      ..writeln(
        '      $sceneTokensSymbol.firstWhere((t) => t.name == name).value;',
      );
  }
  out.writeln('}');
}

/// The declaration imports an opaque type could be spelled through: one per
/// URI (the widest of several — a plain import over a `show`), a prefixed
/// one only when a type carries its prefix, an unprefixed one only when a
/// type carries none. The authoring import was never among them.
List<String> _neededImports(List<String> directives, Set<String> types) {
  var prefixed = {
    for (var t in types)
      if (t.contains('.')) t.substring(0, t.indexOf('.')),
  };
  var bare = types.any((t) => !t.contains('.'));
  var byUri = <String, String>{};
  for (var d in directives) {
    var uri = _importPath(d);
    var prefix = RegExp(r'\bas\s+(\w+)').firstMatch(d)?.group(1);
    var used = prefix == null ? bare : prefixed.contains(prefix);
    if (!used) continue;
    var narrow = d.contains(' show ') || d.contains(' hide ');
    var kept = byUri[uri];
    if (kept == null ||
        (!narrow && (kept.contains(' show ') || kept.contains(' hide ')))) {
      byUri[uri] = d;
    }
  }
  return byUri.values.toList();
}

/// `foo.dart` from `import 'foo.dart' as x;`.
String _importPath(String directive) {
  var q = directive.indexOf("'");
  return directive.substring(q + 1, directive.indexOf("'", q + 1));
}

/// A class with no arguments takes no braces — `const OhohArgs()`, not
/// `const OhohArgs({})`, which is not Dart.
String _formals(List<_Field> fields, {bool defaults = true}) => fields.isEmpty
    ? ''
    : '{${[for (var f in fields) 'this.${f.name}${defaults && f.fallback != null ? ' = ${f.fallback}' : ''}'].join(', ')}}';

/// Which [SceneArgs] reader answers for a type — the four kinds an argument
/// may take, and the whole of what a declaration has to say about one.
String _reader(String type) => switch (type) {
  'String' => 'text',
  'bool' => 'flag',
  'SceneColor' => 'color',
  _ => 'number',
};

/// A track interpolates, so only what has in-between values gets a slot.
bool _animatable(String type) => type == 'double' || type == 'SceneColor';

String _literal(Object value) => switch (value) {
  String s => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'",
  SceneColor c =>
    'const SceneColor(0x${c.argb.toRadixString(16).toUpperCase().padLeft(8, '0')})',
  num n => n == n.roundToDouble() ? '${n.toInt()}.0' : '$n',
  _ => '$value',
};

final _formatter = DartFormatter(
  languageVersion: DartFormatter.latestLanguageVersion,
);
