// The generated half: one arguments class per declared widget, one per scene
// class, and the tracks class that makes a motion typed.
//
// This is where every string in the system that is not in a declaration
// ends up, and nobody types any of them. A scene file writes
// `ExternalNode(const DrinkBadgeArgs(size: 140))` and a motion writes
// `args: DrinkBadgeTracks(size: …)`; both are ordinary Dart the compiler
// checks, and an argument the widget does not declare cannot be spelled.
//
// Only `double` and `SceneColor` arguments get a track slot. A label has no
// in-between values, so animating it is not a refusal here but a name that
// does not exist.
//
// The package's tokens get a class too — `SceneTokens`, a const with one
// typed field per declared token and the declared value as its default —
// so `tokens.brand` in a scene file is a field the compiler checks, and a
// token nobody declared is a name that does not exist.
import 'package:dart_style/dart_style.dart';
import 'package:flutterware/scene_authoring.dart';

import 'externals_file.dart';
import 'group_file.dart';
import 'scene_file.dart';
import 'tokens_file.dart';

/// One scene class the generator writes arguments for, and where it lives
/// relative to the generated file.
class SceneClassDecl {
  SceneClassDecl(
    this.className,
    this.params,
    this.importPath, {
    this.tokensFormal,
  });

  final String className;
  final List<SceneParamDecl> params;

  /// The scene's tokens formal, when it declares one — the generated
  /// arguments class carries the set under that name, so a parent hands
  /// its own down without the author threading anything.
  final String? tokensFormal;

  /// The scene file, relative to the generated file's directory.
  final String importPath;
}

const _header = '''
// GENERATED by the flutterware scene editor. Do not edit.
//
// One arguments class per widget this group declares and per scene class
// in its folder, so a scene file and a motion can name arguments with types
// instead of strings; the group's tokens as one typed class; and the two
// entries the editor's guest boots from. Regenerated whenever the
// declaration, a library or a scene's parameters change; every edit here is
// lost on the next save.
''';

/// The generated file's whole source.
///
/// Imports `scenes.dart` beside it for the widgets and the tokens, and
/// nothing of the libraries: a library's values are literals, spelled here
/// as the class's defaults, and an export is reached through the group at
/// the moment a scene asks.
String emitSceneArgs({
  required List<ExternalWidgetDecl> externals,
  required List<SceneClassDecl> scenes,
  List<SceneTokenDecl> tokens = const [],
  List<String> modes = const [],
  List<String> declarationImports = const [],
  bool entries = true,
}) {
  var hasOpaqueTokens = tokens.any((t) => t.isExport);
  var converts = tokens.any(
    (t) => t.isExport && (t.type == 'Color' || t.type == 'TextStyle'),
  );
  var out = StringBuffer(_header)
    ..writeln()
    ..writeln("import 'package:flutterware/scene_authoring.dart';");
  // The declaration's imports may bring material or cupertino in, which
  // already carry the widgets library; a second door to it is a lint in a
  // file nobody edits. Such an import is emitted whole, below, whatever it
  // showed: the entries need `Widget` and `Builder` from it too.
  var designLibraries = {
    for (var i in declarationImports)
      if (!i.contains(' as ') &&
          (_importPath(i) == 'package:flutter/material.dart' ||
              _importPath(i) == 'package:flutter/cupertino.dart'))
        _importPath(i),
  };
  var widgetsCovered = entries && designLibraries.isNotEmpty;
  if (entries) {
    out.writeln("import 'package:flutter/widget_previews.dart';");
    if (!widgetsCovered) out.writeln("import 'package:flutter/widgets.dart';");
    out
      ..writeln("import 'package:flutterware/previews.dart';")
      ..writeln("import 'package:flutterware/scene.dart';");
  } else if (converts) {
    // The bridge, for `sceneColorOf` and `sceneTextStyleOf`.
    out.writeln("import 'package:flutterware/scene.dart';");
  }
  // The declaration files' own imports come along, because an opaque type —
  // `ButtonStyle`, `app.Thing` — is spelled here exactly as it was spelled
  // there. Only the ones something spelled here needs: an import nothing
  // uses is a warning in a file nobody edits.
  var opaqueTypes = {
    for (var t in tokens)
      if (t.isExport) t.type,
    for (var w in externals)
      for (var a in w.args)
        if (!isValueArgType(a.typeName)) a.typeName,
  };
  var fixed = {
    'package:flutterware/scene_authoring.dart',
    if (entries) ...[
      'package:flutter/widget_previews.dart',
      'package:flutter/widgets.dart',
      'package:flutterware/previews.dart',
      'package:flutterware/scene.dart',
    ],
  };
  var needed = [
    for (var i in _neededImports(declarationImports, opaqueTypes))
      // Already here, or a library — a library declares values, never a
      // type an argument is spelled with.
      if (!fixed.contains(_importPath(i)) &&
          !_importPath(i).endsWith(sceneTokensFileSuffix))
        i,
  ];
  var packages = [
    for (var i in needed)
      if (i.contains("'package:"))
        designLibraries.contains(_importPath(i)) && entries
            ? "import '${_importPath(i)}';"
            : i,
    for (var d in designLibraries)
      if (entries && !needed.any((i) => _importPath(i) == d)) "import '$d';",
  ]..sort();
  for (var i in packages) {
    out.writeln(i);
  }
  var relative = <String, String>{
    for (var i in needed)
      if (!i.contains("'package:")) _importPath(i): i,
  };
  var imports = {
    if (entries || externals.isNotEmpty || hasOpaqueTokens) sceneGroupFileName,
    for (var s in scenes) s.importPath,
    ...relative.keys,
  }.toList()..sort();
  if (imports.isNotEmpty) out.writeln();
  for (var i in imports) {
    out.writeln(relative[i] ?? "import '$i';");
  }

  for (var w in externals) {
    _argsClass(
      out,
      entry: w.entry,
      base: 'SceneExtArgs',
      fields: [
        for (var a in w.args)
          (
            name: a.name,
            type: a.typeName,
            fallback: a.defaultSource,
            opaque: !isValueArgType(a.typeName),
          ),
      ],
      build:
          '  @override\n'
          '  Object build() =>\n'
          "      _external('${w.entry}').build(SceneArgs(toMap()));\n",
    );
  }
  for (var s in scenes) {
    var fields = [
      for (var p in s.params)
        if (p.kind != SceneParamKind.list)
          (
            name: p.name,
            type: p.typeName,
            fallback: _literal(p.defaultValue),
            opaque: false,
          ),
      if (s.tokensFormal case var formal?)
        (
          name: formal,
          type: sceneTokensClassName,
          fallback: 'const $sceneTokensClassName()',
          opaque: true,
        ),
    ];
    _argsClass(
      out,
      entry: s.className,
      base: 'SceneRefArgs',
      fields: fields,
      build:
          '  @override\n'
          '  SceneDefinition build() => ${s.className}('
          '${[for (var f in fields) '${f.name}: ${f.name}'].join(', ')});\n',
    );
  }

  if (tokens.isNotEmpty) _tokensClass(out, tokens, modes);

  if (externals.isNotEmpty) {
    out
      ..writeln()
      ..writeln('/// The declaration an arguments class was generated from —')
      ..writeln('/// how a node builds itself, and why a shipped app hands')
      ..writeln('/// the view nothing.')
      ..writeln('ExternalWidget _external(String entry) =>')
      ..writeln(
        '    $sceneGroupSymbol.widgets.firstWhere((w) => w.entry == entry);',
      );
  }
  if (entries) {
    out
      ..writeln()
      ..writeln("/// The editor's canvas for this group, under the group's")
      ..writeln('/// wrapper — what the editor composites when a scene of this')
      ..writeln('/// folder is open.')
      ..writeln(
        "@Preview(name: 'Scene canvas host', group: '$sceneGuestsPreviewGroup')",
      )
      ..writeln(
        'Widget $sceneCanvasHostSymbol() => SceneCanvasHost.of($sceneGroupSymbol);',
      )
      ..writeln()
      ..writeln('/// A scene and its motion played from a saved pair — what an')
      ..writeln("/// export walks, with this group's widgets and wrapper.")
      ..writeln(
        "@Preview(name: 'Scene player', group: '$sceneGuestsPreviewGroup')",
      )
      ..writeln('Widget $scenePlayerSymbol() => Builder(')
      ..writeln('  builder: (context) => ScenePlayerHost(')
      ..writeln('    $sceneGroupSymbol,')
      ..writeln("    pairPath: context.knobs.string('pair', ''),")
      // A nested scene in the pair names its class; this is how the player
      // instantiates one — the compiled constructor, through the generated
      // arguments class, the way a compiled parent does.
      ..writeln('    nested: const {')
      ..writeln(
        [for (var s in scenes) "      '${s.className}': ${s.className}Args(),"]
            .join('\n'),
      )
      ..writeln('    },')
      ..writeln('  ),')
      ..writeln(');');
  }
  return _formatter.format(out.toString());
}

/// The two entries every generated file declares: the guest the editor
/// composites, and the player an export walks. Found by symbol AND by
/// folder — every group has both.
const sceneCanvasHostSymbol = 'sceneCanvasHost';
const scenePlayerSymbol = 'scenePlayer';

/// Whether a catalog entry at [entryPath] (project-relative) is the host
/// generated in [groupDirectory] (project-relative, `.` for the root).
bool isGroupHostEntry(String entryPath, String groupDirectory) {
  var normalized = entryPath.replaceAll(r'\', '/');
  var expected = groupDirectory == '.' || groupDirectory.isEmpty
      ? sceneArgsFileName
      : '${groupDirectory.replaceAll(r'\', '/')}/$sceneArgsFileName';
  return normalized == expected || normalized == './$expected';
}

/// The preview group the generated entries sit in, so the previews listing
/// folds them together rather than scattering one per folder.
const sceneGuestsPreviewGroup = 'Scene guests';

typedef _Field = ({String name, String type, String? fallback, bool opaque});

void _argsClass(
  StringBuffer out, {
  required String entry,
  required String base,
  required List<_Field> fields,
  required String build,
}) {
  var name = '${entry}Args';
  out
    ..writeln()
    ..writeln('class $name extends $base {')
    ..writeln('  const $name(${_formals(fields)});')
    ..writeln();
  for (var f in fields) {
    out.writeln('  final ${f.type}${f.fallback == null ? '?' : ''} ${f.name};');
  }
  out
    ..writeln()
    ..writeln('  @override')
    ..writeln("  String get entry => '$entry';")
    ..writeln()
    ..writeln('  @override')
    ..writeln('  $name merge(SceneArgs fx) => $name(')
    ..writeln(
      [
        for (var f in fields)
          f.opaque
              // No fx reader: an object has no in-between values, and a
              // track cannot name it.
              ? '        ${f.name}: ${f.name},'
              : "        ${f.name}: fx.${_reader(f.type)}('${f.name}') ?? ${f.name},",
      ].join('\n'),
    )
    ..writeln('      );')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Map<String, Object?> toMap() => {')
    ..writeln(
      [
        // A tokens set is not an argument the editor holds: it stays
        // between the two compiled classes and never reaches the map.
        for (var f in fields)
          if (f.type == sceneTokensClassName)
            ''
          else if (f.fallback == null)
            "        '${f.name}': ?${f.name},"
          else
            "        '${f.name}': ${f.name},",
      ].join('\n'),
    )
    ..writeln('      };')
    ..writeln()
    ..write(build)
    ..writeln('}');

  var tracks = [
    for (var f in fields)
      if (_animatable(f.type)) f,
  ];
  out
    ..writeln()
    ..writeln('class ${entry}Tracks extends SceneExtTracks {')
    ..writeln('  const ${entry}Tracks(${_formals(tracks, defaults: false)});')
    ..writeln();
  for (var f in tracks) {
    out.writeln('  final MotionTrack? ${f.name};');
  }
  out
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Map<String, MotionTrack> toMap() => {')
    ..writeln(
      [for (var f in tracks) "        '${f.name}': ?${f.name},"].join('\n'),
    )
    ..writeln('      };')
    ..writeln('}');
}

/// `class SceneTokens { const SceneTokens({this.brand = const SceneColor(…)
/// …}); final SceneColor brand; … }` — the declared set as a const, so a
/// scene's formal can default to it, and another set (a mode) is the same
/// class with other arguments.
///
/// An opaque token is a getter, not a field: its value is the app's object,
/// which a const cannot hold and this file cannot spell, so it is read from
/// the declaration list at the moment a scene asks — the same move as
/// `_external` below.
void _tokensClass(
  StringBuffer out,
  List<SceneTokenDecl> tokens,
  List<String> declaredModes,
) {
  var values = [
    for (var t in tokens)
      if (t.hasValue) t,
  ];
  var opaque = [
    for (var t in tokens)
      if (t.isExport) t,
  ];
  var formals = values.isEmpty
      ? ''
      : '{${[for (var t in values) 'this.${t.name} = ${_literal(t.value!)}'].join(', ')}}';
  out
    ..writeln()
    ..writeln("/// The tokens this group's libraries declare, typed. A scene")
    ..writeln(
      '/// reads them through its tokens formal — `fill: tokens.brand`;',
    )
    ..writeln('/// the bare constructor is the declared set.')
    ..writeln('class $sceneTokensClassName {')
    ..writeln('  const $sceneTokensClassName($formals);')
    ..writeln();
  for (var t in values) {
    out.writeln('  final ${t.typeName} ${t.name};');
  }
  // One static set per mode name any token carries: the mode's value where
  // the token names it, the default everywhere else. `modes` is the switch
  // a canvas or an app flips.
  var modeNames = {
    ...declaredModes,
    for (var t in values) ...t.modes.keys,
  }.toList()..sort();
  for (var mode in modeNames) {
    // Inside a const set, so a colour is spelled without its own `const`.
    var args = [
      for (var t in values)
        if (t.modes.containsKey(mode))
          '${t.name}: ${_literal(t.modes[mode]!).replaceFirst('const ', '')}',
    ];
    out
      ..writeln()
      ..writeln(
        '  static const $mode = $sceneTokensClassName(${args.join(', ')});',
      );
  }
  if (modeNames.isNotEmpty) {
    out
      ..writeln()
      ..writeln('  /// Every mode the declaration names, by name.')
      ..writeln(
        '  static const modes = <String, $sceneTokensClassName>{${[for (var m in modeNames) "'$m': $m"].join(', ')}};',
      );
  }
  // An export is a getter: the app's own value, read from the group at
  // the moment a scene asks, and converted to the editor's type where the
  // scene needs that — a `Color` on `fill`, a `TextStyle` on `style:`.
  for (var t in opaque) {
    var read = "_token('${t.name}')! as ${t.typeName}";
    var (type, expr) = switch (t.type) {
      'Color' => ('SceneColor', 'sceneColorOf($read)'),
      'TextStyle' => ('SceneTextStyle', 'sceneTextStyleOf($read)'),
      _ => (t.typeName, read),
    };
    out
      ..writeln()
      ..writeln("  /// The app's own, as the group exports it.")
      ..writeln('  $type get ${t.name} => $expr;');
  }
  if (opaque.isNotEmpty) {
    out
      ..writeln()
      ..writeln('  static Object? _token(String name) =>')
      ..writeln(
        '      $sceneGroupSymbol.tokens.firstWhere((t) => t.name == name).value;',
      );
  }
  out.writeln('}');
}

/// The declaration imports an opaque type could be spelled through: one per
/// URI (the widest of several — a plain import over a `show`), a prefixed
/// one only when a type carries its prefix, an unprefixed one only when a
/// type carries none. The authoring import was never among them.
List<String> _neededImports(List<String> directives, Set<String> types) {
  var prefixed = {
    for (var t in types)
      if (t.contains('.')) t.substring(0, t.indexOf('.')),
  };
  var bare = types.any((t) => !t.contains('.'));
  var byUri = <String, String>{};
  for (var d in directives) {
    var uri = _importPath(d);
    var prefix = RegExp(r'\bas\s+(\w+)').firstMatch(d)?.group(1);
    var used = prefix == null ? bare : prefixed.contains(prefix);
    if (!used) continue;
    var narrow = d.contains(' show ') || d.contains(' hide ');
    var kept = byUri[uri];
    if (kept == null ||
        (!narrow && (kept.contains(' show ') || kept.contains(' hide ')))) {
      byUri[uri] = d;
    }
  }
  return [for (var d in byUri.values) _narrowShow(d, types)].nonNulls.toList();
}

/// A `show` list cut down to the names this file spells — the declaration
/// may show more than an export's type, and a shown name nothing uses is a
/// warning in a file nobody edits. Null when nothing shown is used.
String? _narrowShow(String directive, Set<String> types) {
  var match = RegExp(r'\bshow\s+([^;]+);').firstMatch(directive);
  if (match == null) return directive;
  var prefix = RegExp(r'\bas\s+(\w+)').firstMatch(directive)?.group(1);
  var wanted = {
    for (var t in types)
      if (prefix == null && !t.contains('.'))
        t
      else if (prefix != null && t.startsWith('$prefix.'))
        t.substring(prefix.length + 1),
  };
  var shown = match.group(1)!.split(',').map((n) => n.trim()).toList();
  var kept = [
    for (var n in shown)
      if (wanted.contains(n)) n,
  ];
  if (kept.isEmpty) return null;
  if (kept.length == shown.length) return directive;
  return directive.replaceRange(
    match.start,
    match.end,
    'show ${kept.join(', ')};',
  );
}

/// `foo.dart` from `import 'foo.dart' as x;`.
String _importPath(String directive) {
  var q = directive.indexOf("'");
  return directive.substring(q + 1, directive.indexOf("'", q + 1));
}

/// A class with no arguments takes no braces — `const OhohArgs()`, not
/// `const OhohArgs({})`, which is not Dart.
String _formals(List<_Field> fields, {bool defaults = true}) => fields.isEmpty
    ? ''
    : '{${[for (var f in fields) 'this.${f.name}${defaults && f.fallback != null ? ' = ${f.fallback}' : ''}'].join(', ')}}';

/// Which [SceneArgs] reader answers for a type — the four kinds an argument
/// may take, and the whole of what a declaration has to say about one.
String _reader(String type) => switch (type) {
  'String' => 'text',
  'bool' => 'flag',
  'SceneColor' => 'color',
  _ => 'number',
};

String _styleField(String field, Object value) => switch (value) {
  SceneFontWeight w => 'SceneFontWeight.w${w.value}',
  SceneTextAlign a => 'SceneTextAlign.${a.name}',
  int i => '$i',
  var v => _literal(v).replaceFirst('const ', ''),
};

/// A track interpolates, so only what has in-between values gets a slot.
bool _animatable(String type) => type == 'double' || type == 'SceneColor';

String _literal(Object value) => switch (value) {
  // A const context all the way down: the inner colour spells no `const`.
  SceneTextStyle s =>
    'const SceneTextStyle(${[for (var e in s.values.entries) '${e.key}: ${_styleField(e.key, e.value)}'].join(', ')})',
  String s => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'",
  SceneColor c =>
    'const SceneColor(0x${c.argb.toRadixString(16).toUpperCase().padLeft(8, '0')})',
  num n => n == n.roundToDouble() ? '${n.toInt()}.0' : '$n',
  _ => '$value',
};

final _formatter = DartFormatter(
  languageVersion: DartFormatter.latestLanguageVersion,
);
