// GENERATED by the flutterware scene editor. Do not edit.
//
// One arguments class per widget the app declares and per scene class
// beside it, so a scene file and a motion can name arguments with types
// instead of strings. Regenerated whenever a declaration or a scene's
// parameters change; every edit here is lost on the next save.

import 'package:flutterware/scene_authoring.dart';

import 'banner.scene.dart';
import 'invoice.scene.dart';
import 'ohoh.scene.dart';
import 'onboarding.scene.dart';
import 'promo_badge.scene.dart';
import 'scene_externals.dart';
import 'store_banner.scene.dart';
import 'story_card.scene.dart';

class DrinkBadgeArgs extends SceneExtArgs {
  const DrinkBadgeArgs({this.size = 56});

  final double size;

  @override
  String get entry => 'DrinkBadge';

  @override
  DrinkBadgeArgs merge(SceneArgs fx) =>
      DrinkBadgeArgs(size: fx.number('size') ?? size);

  @override
  Map<String, Object?> toMap() => {'size': size};

  @override
  Object build() => _external('DrinkBadge').build(SceneArgs(toMap()));
}

class DrinkBadgeTracks extends SceneExtTracks {
  const DrinkBadgeTracks({this.size});

  final MotionTrack? size;

  @override
  Map<String, MotionTrack> toMap() => {'size': ?size};
}

class SpinnerArgs extends SceneExtArgs {
  const SpinnerArgs({this.size = 36});

  final double size;

  @override
  String get entry => 'Spinner';

  @override
  SpinnerArgs merge(SceneArgs fx) =>
      SpinnerArgs(size: fx.number('size') ?? size);

  @override
  Map<String, Object?> toMap() => {'size': size};

  @override
  Object build() => _external('Spinner').build(SceneArgs(toMap()));
}

class SpinnerTracks extends SceneExtTracks {
  const SpinnerTracks({this.size});

  final MotionTrack? size;

  @override
  Map<String, MotionTrack> toMap() => {'size': ?size};
}

class OrderButtonArgs extends SceneExtArgs {
  const OrderButtonArgs({this.label = 'Order now'});

  final String label;

  @override
  String get entry => 'OrderButton';

  @override
  OrderButtonArgs merge(SceneArgs fx) =>
      OrderButtonArgs(label: fx.text('label') ?? label);

  @override
  Map<String, Object?> toMap() => {'label': label};

  @override
  Object build() => _external('OrderButton').build(SceneArgs(toMap()));
}

class OrderButtonTracks extends SceneExtTracks {
  const OrderButtonTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class BannerSceneArgs extends SceneRefArgs {
  const BannerSceneArgs();

  @override
  String get entry => 'BannerScene';

  @override
  BannerSceneArgs merge(SceneArgs fx) => BannerSceneArgs();

  @override
  Map<String, Object?> toMap() => {};

  @override
  SceneDefinition build() => BannerScene();
}

class BannerSceneTracks extends SceneExtTracks {
  const BannerSceneTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class InvoiceArgs extends SceneRefArgs {
  const InvoiceArgs({
    this.number = 'INV-2043',
    this.issued = '3 September 2026',
    this.billTo = 'Northwind Coffee Ltd',
    this.total = '£1,248.00',
  });

  final String number;
  final String issued;
  final String billTo;
  final String total;

  @override
  String get entry => 'Invoice';

  @override
  InvoiceArgs merge(SceneArgs fx) => InvoiceArgs(
    number: fx.text('number') ?? number,
    issued: fx.text('issued') ?? issued,
    billTo: fx.text('billTo') ?? billTo,
    total: fx.text('total') ?? total,
  );

  @override
  Map<String, Object?> toMap() => {
    'number': number,
    'issued': issued,
    'billTo': billTo,
    'total': total,
  };

  @override
  SceneDefinition build() =>
      Invoice(number: number, issued: issued, billTo: billTo, total: total);
}

class InvoiceTracks extends SceneExtTracks {
  const InvoiceTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class OhohArgs extends SceneRefArgs {
  const OhohArgs();

  @override
  String get entry => 'Ohoh';

  @override
  OhohArgs merge(SceneArgs fx) => OhohArgs();

  @override
  Map<String, Object?> toMap() => {};

  @override
  SceneDefinition build() => Ohoh();
}

class OhohTracks extends SceneExtTracks {
  const OhohTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class OnboardingArgs extends SceneRefArgs {
  const OnboardingArgs({
    this.title = 'Skip the queue',
    this.body = 'Order before you arrive and pick it up from the counter. Every tenth coffee is on us.',
    this.cta = 'Get started',
    this.tint = const SceneColor(0xFFE8632B),
  });

  final String title;
  final String body;
  final String cta;
  final SceneColor tint;

  @override
  String get entry => 'Onboarding';

  @override
  OnboardingArgs merge(SceneArgs fx) => OnboardingArgs(
    title: fx.text('title') ?? title,
    body: fx.text('body') ?? body,
    cta: fx.text('cta') ?? cta,
    tint: fx.color('tint') ?? tint,
  );

  @override
  Map<String, Object?> toMap() => {
    'title': title,
    'body': body,
    'cta': cta,
    'tint': tint,
  };

  @override
  SceneDefinition build() =>
      Onboarding(title: title, body: body, cta: cta, tint: tint);
}

class OnboardingTracks extends SceneExtTracks {
  const OnboardingTracks({this.tint});

  final MotionTrack? tint;

  @override
  Map<String, MotionTrack> toMap() => {'tint': ?tint};
}

class PromoBadgeArgs extends SceneRefArgs {
  const PromoBadgeArgs({
    this.label = 'New',
    this.tint = const SceneColor(0xFFE8632B),
  });

  final String label;
  final SceneColor tint;

  @override
  String get entry => 'PromoBadge';

  @override
  PromoBadgeArgs merge(SceneArgs fx) => PromoBadgeArgs(
    label: fx.text('label') ?? label,
    tint: fx.color('tint') ?? tint,
  );

  @override
  Map<String, Object?> toMap() => {'label': label, 'tint': tint};

  @override
  SceneDefinition build() => PromoBadge(label: label, tint: tint);
}

class PromoBadgeTracks extends SceneExtTracks {
  const PromoBadgeTracks({this.tint});

  final MotionTrack? tint;

  @override
  Map<String, MotionTrack> toMap() => {'tint': ?tint};
}

class StoreBannerArgs extends SceneRefArgs {
  const StoreBannerArgs({
    this.headline = 'Fresh coffee, faster',
    this.subtitle = 'Order ahead. Skip the line. Earn rewards.',
    this.cta = 'Get the app',
    this.tint = const SceneColor(0xFFE8632B),
  });

  final String headline;
  final String subtitle;
  final String cta;
  final SceneColor tint;

  @override
  String get entry => 'StoreBanner';

  @override
  StoreBannerArgs merge(SceneArgs fx) => StoreBannerArgs(
    headline: fx.text('headline') ?? headline,
    subtitle: fx.text('subtitle') ?? subtitle,
    cta: fx.text('cta') ?? cta,
    tint: fx.color('tint') ?? tint,
  );

  @override
  Map<String, Object?> toMap() => {
    'headline': headline,
    'subtitle': subtitle,
    'cta': cta,
    'tint': tint,
  };

  @override
  SceneDefinition build() =>
      StoreBanner(headline: headline, subtitle: subtitle, cta: cta, tint: tint);
}

class StoreBannerTracks extends SceneExtTracks {
  const StoreBannerTracks({this.tint});

  final MotionTrack? tint;

  @override
  Map<String, MotionTrack> toMap() => {'tint': ?tint};
}

class StoryCardArgs extends SceneRefArgs {
  const StoryCardArgs();

  @override
  String get entry => 'StoryCard';

  @override
  StoryCardArgs merge(SceneArgs fx) => StoryCardArgs();

  @override
  Map<String, Object?> toMap() => {};

  @override
  SceneDefinition build() => StoryCard();
}

class StoryCardTracks extends SceneExtTracks {
  const StoryCardTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

/// The declaration an arguments class was generated from —
/// how a node builds itself, and why a shipped app hands
/// the view nothing.
ExternalWidget _external(String entry) =>
    sceneExternals.firstWhere((w) => w.entry == entry);
