// GENERATED by the flutterware scene editor. Do not edit.
//
// One arguments class per widget this group declares and per scene class
// in its folder, so a scene file and a motion can name arguments with types
// instead of strings; the group's tokens as one typed class; and the two
// entries the editor's guest boots from. Regenerated whenever the
// declaration, a library or a scene's parameters change; every edit here is
// lost on the next save.

import 'package:flutterware/scene_authoring.dart';
import 'package:flutter/widget_previews.dart';
import 'package:flutterware/previews.dart';
import 'package:flutterware/scene.dart';
import 'package:flutter/material.dart';

import 'arcade_poster.scene.dart';
import 'banner.scene.dart';
import 'invoice.scene.dart';
import 'ohoh.scene.dart';
import 'onboarding.scene.dart';
import 'phone_home.scene.dart';
import 'promo_badge.scene.dart';
import 'scenes.dart';
import 'showcase.scene.dart';
import 'showcase3d.scene.dart';
import 'store_banner.scene.dart';
import 'store_hero.scene.dart';
import 'story_card.scene.dart';
import 'surface_probe.scene.dart';

class DrinkBadgeArgs extends SceneExtArgs {
  const DrinkBadgeArgs({this.size = 56});

  final double size;

  @override
  String get entry => 'DrinkBadge';

  @override
  DrinkBadgeArgs merge(SceneArgs fx) =>
      DrinkBadgeArgs(size: fx.number('size') ?? size);

  @override
  Map<String, Object?> toMap() => {'size': size};

  @override
  Object build() => _external('DrinkBadge').build(SceneArgs(toMap()));
}

class DrinkBadgeTracks extends SceneExtTracks {
  const DrinkBadgeTracks({this.size});

  final MotionTrack? size;

  @override
  Map<String, MotionTrack> toMap() => {'size': ?size};
}

class SpinnerArgs extends SceneExtArgs {
  const SpinnerArgs({this.size = 36});

  final double size;

  @override
  String get entry => 'Spinner';

  @override
  SpinnerArgs merge(SceneArgs fx) =>
      SpinnerArgs(size: fx.number('size') ?? size);

  @override
  Map<String, Object?> toMap() => {'size': size};

  @override
  Object build() => _external('Spinner').build(SceneArgs(toMap()));
}

class SpinnerTracks extends SceneExtTracks {
  const SpinnerTracks({this.size});

  final MotionTrack? size;

  @override
  Map<String, MotionTrack> toMap() => {'size': ?size};
}

class ModelViewArgs extends SceneExtArgs {
  const ModelViewArgs({
    this.asset = 'assets/models/probe_rig.glb',
    this.yaw = 0,
    this.pitch = 10,
    this.distance = 5,
    this.fov = 45,
    this.clip = 'Open',
    this.clipTime = 0,
  });

  final String asset;
  final double yaw;
  final double pitch;
  final double distance;
  final double fov;
  final String clip;
  final double clipTime;

  @override
  String get entry => 'ModelView';

  @override
  ModelViewArgs merge(SceneArgs fx) => ModelViewArgs(
    asset: fx.text('asset') ?? asset,
    yaw: fx.number('yaw') ?? yaw,
    pitch: fx.number('pitch') ?? pitch,
    distance: fx.number('distance') ?? distance,
    fov: fx.number('fov') ?? fov,
    clip: fx.text('clip') ?? clip,
    clipTime: fx.number('clipTime') ?? clipTime,
  );

  @override
  Map<String, Object?> toMap() => {
    'asset': asset,
    'yaw': yaw,
    'pitch': pitch,
    'distance': distance,
    'fov': fov,
    'clip': clip,
    'clipTime': clipTime,
  };

  @override
  Object build() => _external('ModelView').build(SceneArgs(toMap()));
}

class ModelViewTracks extends SceneExtTracks {
  const ModelViewTracks({
    this.yaw,
    this.pitch,
    this.distance,
    this.fov,
    this.clipTime,
  });

  final MotionTrack? yaw;
  final MotionTrack? pitch;
  final MotionTrack? distance;
  final MotionTrack? fov;
  final MotionTrack? clipTime;

  @override
  Map<String, MotionTrack> toMap() => {
    'yaw': ?yaw,
    'pitch': ?pitch,
    'distance': ?distance,
    'fov': ?fov,
    'clipTime': ?clipTime,
  };
}

class ShotArgs extends SceneExtArgs {
  const ShotArgs({this.path = ''});

  final String path;

  @override
  String get entry => 'Shot';

  @override
  ShotArgs merge(SceneArgs fx) => ShotArgs(path: fx.text('path') ?? path);

  @override
  Map<String, Object?> toMap() => {'path': path};

  @override
  Object build() => _external('Shot').build(SceneArgs(toMap()));
}

class ShotTracks extends SceneExtTracks {
  const ShotTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class OrderButtonArgs extends SceneExtArgs {
  const OrderButtonArgs({this.label = 'Order now', this.style});

  final String label;
  final ButtonStyle? style;

  @override
  String get entry => 'OrderButton';

  @override
  OrderButtonArgs merge(SceneArgs fx) =>
      OrderButtonArgs(label: fx.text('label') ?? label, style: style);

  @override
  Map<String, Object?> toMap() => {'label': label, 'style': ?style};

  @override
  Object build() => _external('OrderButton').build(SceneArgs(toMap()));
}

class OrderButtonTracks extends SceneExtTracks {
  const OrderButtonTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class ArcadePosterArgs extends SceneRefArgs {
  const ArcadePosterArgs({
    this.title = 'GAME OVER',
    this.kicker = 'insert coin to continue',
    this.score = '00128400',
    this.neon = const SceneColor(0xFFFF2D95),
  });

  final String title;
  final String kicker;
  final String score;
  final SceneColor neon;

  @override
  String get entry => 'ArcadePoster';

  @override
  ArcadePosterArgs merge(SceneArgs fx) => ArcadePosterArgs(
    title: fx.text('title') ?? title,
    kicker: fx.text('kicker') ?? kicker,
    score: fx.text('score') ?? score,
    neon: fx.color('neon') ?? neon,
  );

  @override
  Map<String, Object?> toMap() => {
    'title': title,
    'kicker': kicker,
    'score': score,
    'neon': neon,
  };

  @override
  SceneDefinition build() =>
      ArcadePoster(title: title, kicker: kicker, score: score, neon: neon);
}

class ArcadePosterTracks extends SceneExtTracks {
  const ArcadePosterTracks({this.neon});

  final MotionTrack? neon;

  @override
  Map<String, MotionTrack> toMap() => {'neon': ?neon};
}

class BannerSceneArgs extends SceneRefArgs {
  const BannerSceneArgs();

  @override
  String get entry => 'BannerScene';

  @override
  BannerSceneArgs merge(SceneArgs fx) => BannerSceneArgs();

  @override
  Map<String, Object?> toMap() => {};

  @override
  SceneDefinition build() => BannerScene();
}

class BannerSceneTracks extends SceneExtTracks {
  const BannerSceneTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class InvoiceArgs extends SceneRefArgs {
  const InvoiceArgs({
    this.number = 'INV-2043',
    this.issued = '3 September 2026',
    this.billTo = 'Northwind Coffee Ltd',
    this.total = '£1,248.00',
  });

  final String number;
  final String issued;
  final String billTo;
  final String total;

  @override
  String get entry => 'Invoice';

  @override
  InvoiceArgs merge(SceneArgs fx) => InvoiceArgs(
    number: fx.text('number') ?? number,
    issued: fx.text('issued') ?? issued,
    billTo: fx.text('billTo') ?? billTo,
    total: fx.text('total') ?? total,
  );

  @override
  Map<String, Object?> toMap() => {
    'number': number,
    'issued': issued,
    'billTo': billTo,
    'total': total,
  };

  @override
  SceneDefinition build() =>
      Invoice(number: number, issued: issued, billTo: billTo, total: total);
}

class InvoiceTracks extends SceneExtTracks {
  const InvoiceTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class OhohArgs extends SceneRefArgs {
  const OhohArgs();

  @override
  String get entry => 'Ohoh';

  @override
  OhohArgs merge(SceneArgs fx) => OhohArgs();

  @override
  Map<String, Object?> toMap() => {};

  @override
  SceneDefinition build() => Ohoh();
}

class OhohTracks extends SceneExtTracks {
  const OhohTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class OnboardingArgs extends SceneRefArgs {
  const OnboardingArgs({
    this.title = 'Skip the queue',
    this.body = 'Order before you arrive and pick it up from the counter. Every tenth coffee is on us.',
    this.cta = 'Get started',
    this.tint = const SceneColor(0xFFE8632B),
  });

  final String title;
  final String body;
  final String cta;
  final SceneColor tint;

  @override
  String get entry => 'Onboarding';

  @override
  OnboardingArgs merge(SceneArgs fx) => OnboardingArgs(
    title: fx.text('title') ?? title,
    body: fx.text('body') ?? body,
    cta: fx.text('cta') ?? cta,
    tint: fx.color('tint') ?? tint,
  );

  @override
  Map<String, Object?> toMap() => {
    'title': title,
    'body': body,
    'cta': cta,
    'tint': tint,
  };

  @override
  SceneDefinition build() =>
      Onboarding(title: title, body: body, cta: cta, tint: tint);
}

class OnboardingTracks extends SceneExtTracks {
  const OnboardingTracks({this.tint});

  final MotionTrack? tint;

  @override
  Map<String, MotionTrack> toMap() => {'tint': ?tint};
}

class PhoneHomeArgs extends SceneRefArgs {
  const PhoneHomeArgs();

  @override
  String get entry => 'PhoneHome';

  @override
  PhoneHomeArgs merge(SceneArgs fx) => PhoneHomeArgs();

  @override
  Map<String, Object?> toMap() => {};

  @override
  SceneDefinition build() => PhoneHome();
}

class PhoneHomeTracks extends SceneExtTracks {
  const PhoneHomeTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class PromoBadgeArgs extends SceneRefArgs {
  const PromoBadgeArgs({
    this.label = 'New',
    this.tint = const SceneColor(0xFFE8632B),
  });

  final String label;
  final SceneColor tint;

  @override
  String get entry => 'PromoBadge';

  @override
  PromoBadgeArgs merge(SceneArgs fx) => PromoBadgeArgs(
    label: fx.text('label') ?? label,
    tint: fx.color('tint') ?? tint,
  );

  @override
  Map<String, Object?> toMap() => {'label': label, 'tint': tint};

  @override
  SceneDefinition build() => PromoBadge(label: label, tint: tint);
}

class PromoBadgeTracks extends SceneExtTracks {
  const PromoBadgeTracks({this.tint});

  final MotionTrack? tint;

  @override
  Map<String, MotionTrack> toMap() => {'tint': ?tint};
}

class Showcase3DArgs extends SceneRefArgs {
  const Showcase3DArgs();

  @override
  String get entry => 'Showcase3D';

  @override
  Showcase3DArgs merge(SceneArgs fx) => Showcase3DArgs();

  @override
  Map<String, Object?> toMap() => {};

  @override
  SceneDefinition build() => Showcase3D();
}

class Showcase3DTracks extends SceneExtTracks {
  const Showcase3DTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class ShowcaseSceneArgs extends SceneRefArgs {
  const ShowcaseSceneArgs();

  @override
  String get entry => 'ShowcaseScene';

  @override
  ShowcaseSceneArgs merge(SceneArgs fx) => ShowcaseSceneArgs();

  @override
  Map<String, Object?> toMap() => {};

  @override
  SceneDefinition build() => ShowcaseScene();
}

class ShowcaseSceneTracks extends SceneExtTracks {
  const ShowcaseSceneTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class StoreBannerArgs extends SceneRefArgs {
  const StoreBannerArgs({
    this.headline = 'Fresh coffee, faster',
    this.subtitle = 'Order ahead. Skip the line. Earn rewards.',
    this.cta = 'Get the app',
    this.tint = const SceneColor(0xFFE8632B),
    this.tokens = const SceneTokens(),
  });

  final String headline;
  final String subtitle;
  final String cta;
  final SceneColor tint;
  final SceneTokens tokens;

  @override
  String get entry => 'StoreBanner';

  @override
  StoreBannerArgs merge(SceneArgs fx) => StoreBannerArgs(
    headline: fx.text('headline') ?? headline,
    subtitle: fx.text('subtitle') ?? subtitle,
    cta: fx.text('cta') ?? cta,
    tint: fx.color('tint') ?? tint,
    tokens: tokens,
  );

  @override
  Map<String, Object?> toMap() => {
    'headline': headline,
    'subtitle': subtitle,
    'cta': cta,
    'tint': tint,
  };

  @override
  SceneDefinition build() => StoreBanner(
    headline: headline,
    subtitle: subtitle,
    cta: cta,
    tint: tint,
    tokens: tokens,
  );
}

class StoreBannerTracks extends SceneExtTracks {
  const StoreBannerTracks({this.tint});

  final MotionTrack? tint;

  @override
  Map<String, MotionTrack> toMap() => {'tint': ?tint};
}

class StoreHeroArgs extends SceneRefArgs {
  const StoreHeroArgs({
    this.headline = 'Your coffee,\nready before you are',
    this.subtitle = 'Order ahead. Skip the line. Earn rewards.',
    this.cta = 'Get the app',
    this.shotFront = 'build/flutterware/store/flutterware_example/unframed/app-store/iphone-6-9/en-US/01-welcome.png',
    this.shotBack = 'build/flutterware/store/flutterware_example/unframed/app-store/iphone-6-9/en-US/02-menu.png',
    this.tokens = const SceneTokens(),
  });

  final String headline;
  final String subtitle;
  final String cta;
  final String shotFront;
  final String shotBack;
  final SceneTokens tokens;

  @override
  String get entry => 'StoreHero';

  @override
  StoreHeroArgs merge(SceneArgs fx) => StoreHeroArgs(
    headline: fx.text('headline') ?? headline,
    subtitle: fx.text('subtitle') ?? subtitle,
    cta: fx.text('cta') ?? cta,
    shotFront: fx.text('shotFront') ?? shotFront,
    shotBack: fx.text('shotBack') ?? shotBack,
    tokens: tokens,
  );

  @override
  Map<String, Object?> toMap() => {
    'headline': headline,
    'subtitle': subtitle,
    'cta': cta,
    'shotFront': shotFront,
    'shotBack': shotBack,
  };

  @override
  SceneDefinition build() => StoreHero(
    headline: headline,
    subtitle: subtitle,
    cta: cta,
    shotFront: shotFront,
    shotBack: shotBack,
    tokens: tokens,
  );
}

class StoreHeroTracks extends SceneExtTracks {
  const StoreHeroTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class StoryCardArgs extends SceneRefArgs {
  const StoryCardArgs({this.tokens = const SceneTokens()});

  final SceneTokens tokens;

  @override
  String get entry => 'StoryCard';

  @override
  StoryCardArgs merge(SceneArgs fx) => StoryCardArgs(tokens: tokens);

  @override
  Map<String, Object?> toMap() => {};

  @override
  SceneDefinition build() => StoryCard(tokens: tokens);
}

class StoryCardTracks extends SceneExtTracks {
  const StoryCardTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class SurfaceProbeArgs extends SceneRefArgs {
  const SurfaceProbeArgs();

  @override
  String get entry => 'SurfaceProbe';

  @override
  SurfaceProbeArgs merge(SceneArgs fx) => SurfaceProbeArgs();

  @override
  Map<String, Object?> toMap() => {};

  @override
  SceneDefinition build() => SurfaceProbe();
}

class SurfaceProbeTracks extends SceneExtTracks {
  const SurfaceProbeTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

/// The tokens this group's libraries declare, typed. A scene
/// reads them through its tokens formal — `fill: tokens.brand`;
/// the bare constructor is the declared set.
class SceneTokens {
  const SceneTokens({
    this.brand = const SceneColor(0xFFE8632B),
    this.ink = const SceneColor(0xFFFFFFFF),
    this.espresso = const SceneColor(0xFF2B1B12),
    this.radius = 28.0,
    this.title = const SceneTextStyle(
      fontSize: 54.0,
      weight: SceneFontWeight.w700,
    ),
    this.body = const SceneTextStyle(
      fontSize: 20.0,
      color: SceneColor(0xFFD8C9BD),
    ),
  });

  final SceneColor brand;
  final SceneColor ink;
  final SceneColor espresso;
  final double radius;
  final SceneTextStyle title;
  final SceneTextStyle body;

  static const dark = SceneTokens(
    brand: SceneColor(0xFFFF8A5C),
    ink: SceneColor(0xFF1A1208),
    espresso: SceneColor(0xFFF3E9E1),
  );

  /// Every mode the declaration names, by name.
  static const modes = <String, SceneTokens>{'dark': dark};

  /// The app's own, as the group exports it.
  SceneColor get shopBrand => sceneColorOf(_token('shopBrand')! as Color);

  /// The app's own, as the group exports it.
  SceneTextStyle get shopSubtitle =>
      sceneTextStyleOf(_token('shopSubtitle')! as TextStyle);

  /// The app's own, as the group exports it.
  ButtonStyle get ctaStyle => _token('ctaStyle')! as ButtonStyle;

  static Object? _token(String name) =>
      scenes.tokens.firstWhere((t) => t.name == name).value;
}

/// The declaration an arguments class was generated from —
/// how a node builds itself, and why a shipped app hands
/// the view nothing.
ExternalWidget _external(String entry) =>
    scenes.widgets.firstWhere((w) => w.entry == entry);

/// The editor's canvas for this group, under the group's
/// wrapper — what the editor composites when a scene of this
/// folder is open.
@Preview(name: 'Scene canvas host', group: 'Scene guests')
Widget sceneCanvasHost() => SceneCanvasHost.of(scenes);

/// A scene and its motion played from a saved pair — what an
/// export walks, with this group's widgets and wrapper.
@Preview(name: 'Scene player', group: 'Scene guests')
Widget scenePlayer() => Builder(
  builder: (context) => ScenePlayerHost(
    scenes,
    pairPath: context.knobs.string('pair', ''),
    nested: const {
      'ArcadePoster': ArcadePosterArgs(),
      'BannerScene': BannerSceneArgs(),
      'Invoice': InvoiceArgs(),
      'Ohoh': OhohArgs(),
      'Onboarding': OnboardingArgs(),
      'PhoneHome': PhoneHomeArgs(),
      'PromoBadge': PromoBadgeArgs(),
      'Showcase3D': Showcase3DArgs(),
      'ShowcaseScene': ShowcaseSceneArgs(),
      'StoreBanner': StoreBannerArgs(),
      'StoreHero': StoreHeroArgs(),
      'StoryCard': StoryCardArgs(),
      'SurfaceProbe': SurfaceProbeArgs(),
    },
  ),
);
