import 'dart:io';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:dart_style/dart_style.dart';
import 'package:flutterware_app/src/previews/catalog_entry.dart';
import 'package:flutterware_app/src/previews/catalog_wrapper.dart';
import 'package:flutterware_app/src/previews/discovery.dart';
import 'package:flutterware_app/src/utils/source_code/escape_dart_string.dart';
import 'package:path/path.dart' as p;

/// Writes the table of the example's previews the web demo compiles in:
/// `web_demo/demo/entries.g.dart` and a wrapper per entry beside it.
///
/// Outside `lib/` on purpose, like the example's own previews: a file under
/// `lib/` is addressed by a `package:` URI, and a relative import from one
/// cannot leave the package — where these wrappers have to reach the
/// example's demos, which have no `package:` URI of their own.
///
/// ```sh
/// cd app && fvm dart run tool/demo/web_entries.dart
/// ```
///
/// The wrappers are the same the guest entrypoint uses — the annotation
/// evaluated in the demo's own scope, the builder reached by name — written
/// by the same writer, so an entry is staged in the browser exactly as it is
/// in an embedder process. The table is what `runWebDemo` hands the previews
/// panel: the scan, and how to build each entry.
///
/// **Curated, not everything.** The page shows the coffee shop — the same
/// app the recorded scenarios walk — so the entries are the ones in
/// [webDemoEntryIds] and no other; the example's probes stay out of the
/// demo. Each is still checked for what a browser can run: `dart:ffi` does
/// not compile for the web at all; a scene needs the GPU and its host reads
/// the disk; the shop's database is native. A curated entry whose import
/// closure — followed through the example and through `package:flutterware`
/// — reaches any of those fails this script rather than quietly dropping
/// out. `dart:io` alone is not a reason: it compiles to stubs that throw
/// only when called, and the studio's own libraries carry it everywhere a
/// desktop feature lives — but an example file of its own importing it is
/// one that will call it, so that is. Deterministic, and CI regenerates it
/// and expects no diff.
void main(List<String> arguments) {
  var appRoot = p.dirname(p.dirname(p.dirname(p.fromUri(Platform.script))));
  var repoRoot = p.dirname(appRoot);
  var example = p.join(repoRoot, 'examples', 'example');
  var out = p.join(repoRoot, 'web_demo', 'demo');
  var wrappers = p.join(out, 'entries');
  if (Directory(wrappers).existsSync()) {
    Directory(wrappers).deleteSync(recursive: true);
  }

  var scanned = CatalogScanner(projectRoot: example).scan();
  var byId = {for (var entry in scanned.entries) entry.id: entry};
  var cleanliness = _Cleanliness(example: example, flutterware: repoRoot);
  var kept = <(int, CatalogEntry)>[];
  var writer = CatalogWrapperWriter(outputDir: wrappers, projectRoot: example);
  // Formatted as `tool/prepare_submit.dart` formats, so what is committed is
  // what a regeneration in CI produces.
  var formatter = DartFormatter(
    languageVersion: DartFormatter.latestLanguageVersion,
  );
  var index = 0;
  for (var id in webDemoEntryIds) {
    var entry = byId[id];
    if (entry == null) {
      stderr.writeln(
        'No preview $id in the example. Known: ${byId.keys.join(', ')}',
      );
      exit(1);
    }
    if (cleanliness.unfitReasonOf(p.join(example, entry.path)) case var why?) {
      stderr.writeln('$id cannot run in a browser: $why');
      exit(1);
    }
    File(p.join(wrappers, 'entry_$index.dart'))
      ..parent.createSync(recursive: true)
      ..writeAsStringSync(formatter.format(writer.source(entry, index)));
    kept.add((index, entry));
    index++;
  }

  var buffer = StringBuffer()
    ..writeln('// GENERATED by tool/demo/web_entries.dart — do not edit.')
    ..writeln('// ignore_for_file: implementation_imports')
    ..writeln('//')
    ..writeln('// The previews the web demo shows — the coffee shop, a screen')
    ..writeln('// at a time — with a wrapper per entry beside this file.')
    ..writeln("import 'package:flutterware/previews_guest.dart';")
    ..writeln(
      "import 'package:flutterware_app/src/previews/catalog_entry.dart';",
    )
    ..writeln(
      "import 'package:flutterware_app/src/previews/inline_guest.dart';",
    )
    ..writeln();
  for (var (i, _) in kept) {
    buffer.writeln("import 'entries/entry_$i.dart' as e$i;");
  }
  buffer
    ..writeln()
    ..writeln('const webDemoEntries = <CatalogEntry>[');
  for (var (_, entry) in kept) {
    buffer.writeln('  CatalogEntry(');
    buffer.writeln('    path: ${escapeDartString(entry.path)},');
    buffer.writeln('    symbol: ${escapeDartString(entry.symbol)},');
    buffer.writeln('    annotation: ${escapeDartString(entry.annotation)},');
    buffer.writeln('    name: ${escapeDartString(entry.name)},');
    if (entry.group != null) {
      buffer.writeln('    group: ${escapeDartString(entry.group!)},');
    }
    if (entry.declaredId != null) {
      buffer.writeln('    declaredId: ${escapeDartString(entry.declaredId!)},');
    }
    if (entry.ordinal != 0) buffer.writeln('    ordinal: ${entry.ordinal},');
    buffer.writeln('    line: ${entry.line},');
    buffer.writeln('    endLine: ${entry.endLine},');
    buffer.writeln('  ),');
  }
  buffer
    ..writeln('];')
    ..writeln()
    ..writeln(
      'CatalogEntryBuilder? webDemoEntryOf(String id) => switch (id) {',
    );
  for (var (i, entry) in kept) {
    buffer.writeln(
      '  ${escapeDartString(entry.id)} => '
      '(preview: e$i.fwPreview, builder: e$i.fwBuilder),',
    );
  }
  buffer
    ..writeln('  _ => null,')
    ..writeln('};')
    ..writeln()
    ..writeln('InlinePreviews get webDemoPreviews =>')
    ..writeln('    (entries: webDemoEntries, entryOf: webDemoEntryOf);');
  File(p.join(out, 'entries.g.dart'))
      .writeAsStringSync(formatter.format(buffer.toString()));
  print('Wrote ${kept.length} entries to ${p.relative(out, from: repoRoot)}');
}

/// What the page shows, in this order: the coffee shop's screens.
const webDemoEntryIds = [
  'demo/brand.dart#appIcon',
  'demo/shop.dart#shopWelcome',
  'demo/shop.dart#shopMenu',
  'demo/shop.dart#shopDrink',
  'demo/shop.dart#shopCart',
  'demo/shop.dart#shopConfirmation',
];

/// Whether a file's import closure stays in what a browser can compile.
///
/// Followed through this package's own files and through `package:flutterware`
/// — the two places a preview's code lives — and stopped at every other
/// package, which is judged by name. A conditional import follows its
/// `dart.library.js_interop` branch, which is the one a web build takes.
class _Cleanliness {
  _Cleanliness({required this.example, required this.flutterware});

  final String example;
  final String flutterware;
  final _verdicts = <String, String?>{};

  /// Fatal anywhere: no web compile, or no way to run.
  static const _unfitLibraries = {'dart:ffi'};

  /// Fatal in the example's own files, where an import is a use.
  static const _unfitInExample = {'dart:io', 'dart:isolate'};

  /// The studio's libraries that need a machine underneath them.
  static const _unfitFlutterware = {
    'package:flutterware/scene.dart',
    'package:flutterware/scene_authoring.dart',
    'package:flutterware/server.dart',
    'package:flutterware/render_client.dart',
  };

  static const _unfitPackages = {
    'flutter_scene',
    'flutter_gpu',
    'sqlite3',
    'sqlite_async',
    'hooks',
    'path_provider',
    'device_info_plus',
    'android_id',
    'package_info_plus',
    'flutter_secure_storage',
  };

  String? _packageName;

  String? unfitReasonOf(String file) {
    if (_verdicts.containsKey(file)) return _verdicts[file];
    // Provisionally clean while it is being walked, so a cycle does not recurse.
    _verdicts[file] = null;
    var verdict = _walk(file);
    _verdicts[file] = verdict;
    return verdict;
  }

  String? _walk(String file) {
    if (!File(file).existsSync()) return null;
    var unit = parseString(
      content: File(file).readAsStringSync(),
      throwIfDiagnostics: false,
    ).unit;
    for (var directive in unit.directives) {
      if (directive is! NamespaceDirective) continue;
      var uri = _webUriOf(directive);
      if (uri == null) continue;
      var own = p.isWithin(example, file);
      if (_unfitLibraries.contains(uri) ||
          (own && _unfitInExample.contains(uri)) ||
          _unfitFlutterware.contains(uri)) {
        return '${p.relative(file, from: example)} imports $uri';
      }
      if (uri.startsWith('dart:')) continue;
      var resolved = _resolve(uri, from: file);
      if (resolved == null) {
        var package = uri.startsWith('package:')
            ? uri.substring('package:'.length).split('/').first
            : null;
        if (package != null && _unfitPackages.contains(package)) {
          return '${p.relative(file, from: example)} imports $uri';
        }
        continue;
      }
      if (unfitReasonOf(resolved) case var reason?) return reason;
    }
    return null;
  }

  /// The URI a web build takes: the `js_interop` configuration when the
  /// directive has one, the default otherwise.
  String? _webUriOf(NamespaceDirective directive) {
    for (var configuration in directive.configurations) {
      var name = configuration.name.toSource();
      if (name == 'dart.library.js_interop' || name == 'dart.library.html') {
        return configuration.uri.stringValue;
      }
    }
    return directive.uri.stringValue;
  }

  String? _resolve(String uri, {required String from}) {
    if (uri.startsWith('package:')) {
      var rest = uri.substring('package:'.length);
      var slash = rest.indexOf('/');
      var package = rest.substring(0, slash);
      var path = rest.substring(slash + 1);
      if (package == 'flutterware') {
        return p.join(flutterware, 'lib', p.joinAll(p.url.split(path)));
      }
      if (package == (_packageName ??= _readPackageName())) {
        return p.join(example, 'lib', p.joinAll(p.url.split(path)));
      }
      return null;
    }
    return p.normalize(p.join(p.dirname(from), p.joinAll(p.url.split(uri))));
  }

  String _readPackageName() {
    var pubspec = File(p.join(example, 'pubspec.yaml')).readAsLinesSync();
    for (var line in pubspec) {
      if (line.startsWith('name:')) return line.substring(5).trim();
    }
    return 'flutterware_example';
  }
}
