import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:pubspec_parse/pubspec_parse.dart';

import 'package:flutterware/channels.dart';

import '../utils/parameter_knobs.dart';
import 'entrypoint_knobs.dart';
import 'wrapper_import.dart';

/// What a launch should pass to `--target`: the generated guest wrapper when
/// one could be written, the plain [entrypoint] otherwise, with the reason.
class GuestEntrypoint {
  GuestEntrypoint._(this.target, {required this.guest, this.reason});

  /// Package-relative, `/`-separated — what `--target` takes.
  final String target;

  /// Whether [target] wraps the entrypoint in the run guest. False means the
  /// app will run uninstrumented: inspect over the bare VM service, no act.
  final bool guest;

  /// Why wrapping was skipped, when it was.
  final String? reason;
}

/// Writes the wrapper entrypoint that installs the run guest around
/// [entrypoint] — what turns a plain `flutter run` into a driveable app.
///
/// The wrapper lives under `.dart_tool/flutterware/run/`, inside the package
/// so its imports resolve, outside `lib/` so no analyzer or tool of the
/// project's ever meets it. Regenerated on every launch: it is derived state,
/// and the entrypoint it wraps may have moved since last time.
///
/// **Wrapping needs the entrypoint to be inside the package, and nothing
/// more.** It used to require `lib/`, on the grounds that the wrapper needs a
/// `package:` URI to import — but the wrapper sits inside the package, so a
/// path reaches anything the package holds, and a file outside `lib/` has no
/// `package:` spelling for a path to conflict with. [wrapperImportOf] draws
/// that line. This matters because `demo/` and `tool/` are where dev-only entry
/// points belong in a project that keeps them out of what it ships — the same
/// `demo/` the previews plugin already scans, so refusing it here made one
/// config file disagree with itself.
///
/// A `lib/` entrypoint still needs the package's name, because there a
/// `package:` URI is the *only* spelling allowed. When it or the entrypoint is
/// out of reach the launch proceeds uninstrumented rather than failing —
/// stated in [GuestEntrypoint.reason], which the caller logs.
///
/// [targetsWeb] withdraws the path spelling, because the browser's compiler
/// does not share the file system the path is a fact about — the whole of the
/// why is on [webWrapperImportRefusal]. Passed in rather than sniffed from the
/// entrypoint: the same file is wrapped on a phone and refused on Chrome, so it
/// is the launch that decides, never the file.
///
/// [knobs] are the values to pass `main` as named arguments, keyed by parameter
/// name — `2026-08-12-run-knobs-design.md` § K3. Rewriting this file and hot
/// restarting is what makes changing one cost 262ms rather than a rebuild, so
/// the same function has to produce it at launch *and* on a knob change, or the
/// two drift.
GuestEntrypoint writeGuestEntrypoint({
  required String packageRoot,
  required String entrypoint,
  Map<String, Object?> knobs = const {},
  bool targetsWeb = false,
}) {
  String? package;
  Object? packageProblem;
  try {
    package = Pubspec.parse(
      File(p.join(packageRoot, 'pubspec.yaml')).readAsStringSync(),
    ).name;
  } catch (e) {
    // Only fatal for a `lib/` entrypoint, which has no other spelling. Held
    // rather than reported here so an entrypoint that does not need the name is
    // not refused for missing it.
    packageProblem = e;
  }
  var importUri = wrapperImportOf(
    entrypoint,
    package: package,
    web: targetsWeb,
  );
  if (importUri == null) {
    // Ordered by which fact is the *reason*. Outside the package first: that
    // one is true on every platform, so reporting web at it would name the
    // launch's device for a refusal the device did not cause.
    var reason = switch (entrypoint) {
      _ when !p.posix.isWithin('.', entrypoint) =>
        '$entrypoint is outside $packageRoot, so the wrapper written inside '
            'it has no import that reaches the entrypoint',
      _ when p.posix.isWithin('lib', entrypoint) =>
        'could not read the package name from pubspec.yaml, and a lib/ '
            'entrypoint has to be imported by its package: URI: '
            '$packageProblem',
      _ => webWrapperImportRefusal(entrypoint)!,
    };
    return GuestEntrypoint._(entrypoint, guest: false, reason: reason);
  }
  var target = p.posix.join(
    wrapperDirectory,
    '${p.basenameWithoutExtension(entrypoint)}_guest.dart',
  );
  var scan = knobs.isEmpty
      ? const EntrypointKnobs()
      : scanEntrypointKnobs(packageRoot: packageRoot, entrypoint: entrypoint);
  var arguments = _arguments(knobs, scan.knobs);

  File(p.joinAll([packageRoot, ...p.posix.split(target)]))
    ..parent.createSync(recursive: true)
    ..writeAsStringSync('''
// GENERATED by flutterware run — regenerated on every launch, do not edit.
//
// Wraps the app's own main in the run guest, which serves inspection (tree,
// logs, errors) and the drive transaction (ext.flutterware.act) over the VM
// service. Compiling this needs `flutterware` and `flutter_test` in the
// project's dev_dependencies.
${arguments.isEmpty ? "import 'dart:async';\n\n" : ''}import 'package:flutterware/run_guest.dart' as guest;
${arguments.isEmpty ? '' : '''
// The entry point's own imports, so a value written here can name what the
// entry point names — an enum declared anywhere but this file is otherwise
// `Undefined name`. Unused ones are ordinary: nothing analyses this file.
${scan.imports.join('\n')}
'''}
import '$importUri' as entry;
${arguments.isEmpty ? '''

// Checked at runtime because the signature cannot be known here: an app's
// main legally takes `List<String> args`, and a wrapper assuming zero
// parameters turns that app's launch into a compile failure. `Object?`
// rather than `var`, so both branches type-check whatever shape this
// particular main has.
void main(List<String> args) {
  Object? entryMain = entry.main;
  if (entryMain is FutureOr<void> Function(List<String>)) {
    guest.runGuest(() => entryMain(args));
  } else {
    guest.runGuest(entryMain as FutureOr<void> Function());
  }''' : '''

// Named arguments rather than the runtime shape check the other branch does:
// a main taking knobs is called with them by name, so the compiler checks
// this call and a value for a parameter that moved fails the build here
// rather than doing nothing at runtime.
void main(List<String> args) {
  guest.runGuest(() => entry.main(
$arguments      ));'''}
}
''');
  return GuestEntrypoint._(target, guest: true);
}

/// The named arguments to pass `main`, one indented line each.
///
/// Only knobs the signature actually declares: a value for a parameter that is
/// not there would not compile, and refusing to write it turns a stale wish
/// into a knob that does nothing rather than a launch that fails.
///
/// A picker's value is a bare constant name, so it is written back through the
/// type the entry point wrote — `staging` becomes `m.Backend.staging`.
///
/// A value for a knob the signature *does* declare, which cannot be written as
/// its type, throws. Dropping it was the quiet version of the same mistake: the
/// wrapper came out with no arguments at all, so the app ran on its defaults
/// while the run's handle showed the value that was asked for. Callers check
/// first — this is the line that makes a gap in that checking loud.
String _arguments(Map<String, Object?> values, List<ParameterKnob> declared) {
  var byName = {for (var knob in declared) knob.name: knob};
  var lines = <String>[];
  for (var MapEntry(key: name, value: value) in values.entries) {
    var knob = byName[name];
    // Not an error: a config can name a parameter that has since moved, and a
    // stale wish should be a knob that does nothing rather than a launch that
    // cannot start.
    if (knob == null || value == null) continue;
    var literal = _literalFor(knob, value);
    if (literal == null) {
      throw ArgumentError.value(
        value,
        name,
        'is not a ${knob.knob.kind.name} ${knob.enumType ?? ''}'.trimRight(),
      );
    }
    lines.add('        $name: $literal,\n');
  }
  return lines.join();
}

/// A value as Dart source, written for the type the **signature** declares.
///
/// Not for the value's own runtime type — that was the bug an end-to-end launch
/// found and the unit tests could not. Every value arriving from the CLI or MCP
/// is a `String`, so an `int` parameter was handed `r'8186'` and the build died
/// on *String can't be assigned to int*. The parameter list is the only thing
/// that knows what a value is meant to be.
///
/// Null for a value that does not fit its kind. Both launch paths and
/// `setKnobs` refuse those before anything is written; [_arguments] turns what
/// is left into a throw, so a bad value can never reach the compiler as
/// generated source *nor* be silently left out of it.
String? _literalFor(ParameterKnob knob, Object? value) {
  var text = '$value';
  return switch (knob.knob.kind) {
    // Checked against the constants, not merely spelled through the type. A
    // script source can compute a value for an enum knob that the enum does not
    // declare, and `Backend.whatever` is a perfectly writable literal that does
    // not compile — a build failure in a file nobody wrote.
    KnobKind.picker =>
      knob.enumType == null || !knob.knob.options.contains(text)
          ? null
          : '${knob.enumType}.$text',
    KnobKind.integer => int.tryParse(text)?.toString(),
    KnobKind.number => double.tryParse(text)?.toString(),
    KnobKind.boolean => switch (text) {
      'true' => 'true',
      'false' => 'false',
      _ => null,
    },
    KnobKind.string => _stringLiteral(text),
  };
}

/// Strings are quoted `r'...'` unless they carry something a raw string cannot
/// — a URL or a Windows path then arrives with no escaping to get wrong, which
/// is the shape a knob's value tends to have.
///
/// **A line break disqualifies both forms until it is escaped.** A single-quoted
/// literal cannot span lines whether it is raw or not, so a value carrying one
/// closed the string mid-way and left the wrapper unparseable — reported as a
/// syntax error in generated source, about a value the user typed somewhere
/// else. A script source cannot produce one (`define_scripts` refuses
/// multi-line output outright), but a caller can: a JSON `"\n"` over MCP is one
/// character, and so is a paste into the field.
String _stringLiteral(String value) {
  var plain =
      !value.contains("'") &&
      !value.contains(r'$') &&
      !value.contains('\n') &&
      !value.contains('\r');
  if (plain) return "r'$value'";
  // Backslash first, or every escape written after it is escaped again.
  var escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r');
  return "'$escaped'";
}
