import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:pubspec_parse/pubspec_parse.dart';

/// What a launch should pass to `--target`: the generated guest wrapper when
/// one could be written, the plain [entrypoint] otherwise, with the reason.
class GuestEntrypoint {
  GuestEntrypoint._(this.target, {required this.guest, this.reason});

  /// Package-relative, `/`-separated — what `--target` takes.
  final String target;

  /// Whether [target] wraps the entrypoint in the run guest. False means the
  /// app will run uninstrumented: inspect over the bare VM service, no act.
  final bool guest;

  /// Why wrapping was skipped, when it was.
  final String? reason;
}

/// Writes the wrapper entrypoint that installs the run guest around
/// [entrypoint] — what turns a plain `flutter run` into a driveable app.
///
/// The wrapper lives under `.dart_tool/flutterware/run/`, inside the package
/// so its imports resolve, outside `lib/` so no analyzer or tool of the
/// project's ever meets it. Regenerated on every launch: it is derived state,
/// and the entrypoint it wraps may have moved since last time.
///
/// Wrapping needs a `package:` URI for the entrypoint (so `lib/` only) and
/// the package's name. When either is missing the launch proceeds
/// uninstrumented rather than failing — stated in [GuestEntrypoint.reason],
/// which the caller logs.
GuestEntrypoint writeGuestEntrypoint({
  required String packageRoot,
  required String entrypoint,
}) {
  if (!entrypoint.startsWith('lib/')) {
    return GuestEntrypoint._(
      entrypoint,
      guest: false,
      reason:
          '$entrypoint is not under lib/, so it has no package: URI the '
          'wrapper could import',
    );
  }
  String package;
  try {
    package = Pubspec.parse(
      File(p.join(packageRoot, 'pubspec.yaml')).readAsStringSync(),
    ).name;
  } catch (e) {
    return GuestEntrypoint._(
      entrypoint,
      guest: false,
      reason: 'could not read the package name from pubspec.yaml: $e',
    );
  }
  var importUri = 'package:$package/${entrypoint.substring('lib/'.length)}';
  var target = p.posix.join(
    '.dart_tool',
    'flutterware',
    'run',
    '${p.basenameWithoutExtension(entrypoint)}_guest.dart',
  );
  File(p.joinAll([packageRoot, ...p.posix.split(target)]))
    ..parent.createSync(recursive: true)
    ..writeAsStringSync('''
// GENERATED by flutterware run — regenerated on every launch, do not edit.
//
// Wraps the app's own main in the run guest, which serves inspection (tree,
// logs, errors) and the drive transaction (ext.flutterware.act) over the VM
// service. Compiling this needs `flutterware` and `flutter_test` in the
// project's dev_dependencies.
import 'dart:async';

import 'package:flutterware/run_guest.dart';

import '$importUri' as entry;

// Checked at runtime because the signature cannot be known here: an app's
// main legally takes `List<String> args`, and a wrapper assuming zero
// parameters turns that app's launch into a compile failure. `Object?`
// rather than `var`, so both branches type-check whatever shape this
// particular main has.
void main(List<String> args) {
  Object? entryMain = entry.main;
  if (entryMain is FutureOr<void> Function(List<String>)) {
    runGuest(() => entryMain(args));
  } else {
    runGuest(entryMain as FutureOr<void> Function());
  }
}
''');
  return GuestEntrypoint._(target, guest: true);
}
