// GENERATED by tool/icon/generate.dart from fw_tile_base.svg. Do not edit.
//
// Where a project's icon is drawn on the composited tile, in the tile's own
// 1024-unit space. Authored in the SVG so the picture and the number cannot
// disagree.

/// The chip's square, in tile units.
const tileChipLeft = 672.0;
const tileChipTop = 425.2;
const tileChipSize = 231.4;

/// The tile the numbers above are expressed in.
const tileCanvas = 1024.0;

/// Corner radius of the chip, echoing the tile's own ratio.
const tileChipRadius = tileChipSize * 0.225;

/// The hairline that keeps a dark project icon from sinking into the tile.
/// Unconditional: the alternative needed a darkness classifier, and the first
/// one written read the wrong HSL channel and inverted its answer.
const tileChipHairlineWidth = 6.0;
const tileChipHairlineOpacity = 0.35;
