// GENERATED by tool/generate_capabilities.dart. Do not edit by hand.
//
// ignore_for_file: avoid_escaping_inner_quotes
//
// The wire shape of every action result, read out of the classes themselves.
// `test/session/action_shapes_test.dart` fails when this no longer matches the
// source, so editing it by hand only postpones the disagreement.

import 'package:flutterware/plugins.dart';

/// Result shapes by class name — look one up with `PluginAction.returnsName`.
final resultShapes = <String, ResultShape>{
  'CatalogBrokenEntry': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogBrokenEntry',
    'fields': <Object?>[
      <String, Object?>{'name': 'id', 'type': 'String'},
      <String, Object?>{
        'name': 'error',
        'type': 'String',
        'doc': 'The compiler\'s diagnostics, verbatim.',
      },
    ],
  }),
  'CatalogCheckResult': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogCheckResult',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'packages',
        'type': 'List<CatalogPackageCheck>',
        'shape': <String, Object?>{
          'type': 'CatalogPackageCheck',
          'fields': <Object?>[
            <String, Object?>{'name': 'path', 'type': 'String'},
            <String, Object?>{
              'name': 'ok',
              'type': 'bool',
              'doc': 'True when nothing is quarantined.',
            },
            <String, Object?>{
              'name': 'servable',
              'type': 'List<String>',
              'doc': 'Entry ids the compiler built.',
            },
            <String, Object?>{
              'name': 'broken',
              'type': 'List<CatalogBrokenEntry>',
              'shape': <String, Object?>{
                'type': 'CatalogBrokenEntry',
                'fields': <Object?>[
                  <String, Object?>{'name': 'id', 'type': 'String'},
                  <String, Object?>{
                    'name': 'error',
                    'type': 'String',
                    'doc': 'The compiler\'s diagnostics, verbatim.',
                  },
                ],
              },
            },
            <String, Object?>{
              'name': 'error',
              'type': 'String',
              'optional': true,
              'doc':
                  'Set when the daemon could not be reached at all, which is not the same as "everything failed to compile".',
            },
          ],
        },
      },
    ],
  }),
  'CatalogEntriesResult': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogEntriesResult',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'packages',
        'type': 'List<CatalogPackageEntries>',
        'shape': <String, Object?>{
          'type': 'CatalogPackageEntries',
          'fields': <Object?>[
            <String, Object?>{
              'name': 'path',
              'type': 'String',
              'doc': 'Package path as declared in `tool/flutterware.dart`.',
            },
            <String, Object?>{
              'name': 'entries',
              'type': 'List<CatalogEntrySummary>',
              'shape': <String, Object?>{
                'type': 'CatalogEntrySummary',
                'fields': <Object?>[
                  <String, Object?>{
                    'name': 'id',
                    'type': 'String',
                    'doc':
                        'What `screenshot --entry` and `describe --entry` take.',
                  },
                  <String, Object?>{'name': 'name', 'type': 'String'},
                  <String, Object?>{
                    'name': 'address',
                    'type': 'String',
                    'doc':
                        'The `Address`, rendered — hand it back to `screenshot`, or later `show`.',
                  },
                  <String, Object?>{
                    'name': 'group',
                    'type': 'String',
                    'optional': true,
                    'doc':
                        'One tree level between the directory and the leaf, when the entry declares or derives one.',
                  },
                  <String, Object?>{
                    'name': 'formFactor',
                    'type': 'String',
                    'optional': true,
                    'doc':
                        '`mobile`, `desktop`, `all` — what the demo says it is *for*, when it says.',
                  },
                ],
              },
            },
            <String, Object?>{
              'name': 'diagnostics',
              'type': 'List<String>',
              'doc':
                  'Discovery\'s complaints — a duplicate id, an uncallable target.',
            },
            <String, Object?>{
              'name': 'error',
              'type': 'String',
              'optional': true,
              'doc':
                  'Set when the scan failed, in which case [entries] is empty and means nothing.',
            },
          ],
        },
      },
    ],
  }),
  'CatalogEntryDescription': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogEntryDescription',
    'fields': <Object?>[
      <String, Object?>{'name': 'id', 'type': 'String'},
      <String, Object?>{'name': 'name', 'type': 'String'},
      <String, Object?>{
        'name': 'package',
        'type': 'String',
        'doc': 'Which declared package holds it.',
      },
      <String, Object?>{
        'name': 'file',
        'type': 'String',
        'doc': 'Project-relative path of the declaring file.',
      },
      <String, Object?>{
        'name': 'symbol',
        'type': 'String',
        'doc': 'The annotated top-level function.',
      },
      <String, Object?>{
        'name': 'annotation',
        'type': 'String',
        'doc':
            'The annotation\'s source text, verbatim — `Demo(name: \'Counter\')`.',
      },
      <String, Object?>{'name': 'address', 'type': 'String'},
      <String, Object?>{'name': 'group', 'type': 'String', 'optional': true},
      <String, Object?>{
        'name': 'formFactor',
        'type': 'String',
        'optional': true,
      },
      <String, Object?>{
        'name': 'knobs',
        'type': 'List<CatalogKnob>',
        'optional': true,
        'doc':
            'Present only when `--knobs` asked for them: reading a knob costs a compile and a frame, so absent means "not looked at" while an empty list means "this entry declares none".',
        'shape': <String, Object?>{
          'type': 'CatalogKnob',
          'fields': <Object?>[
            <String, Object?>{'name': 'name', 'type': 'String'},
            <String, Object?>{
              'name': 'kind',
              'type': 'String',
              'doc': '`string`, `boolean`, `integer`, `number`, `picker`.',
            },
            <String, Object?>{
              'name': 'value',
              'type': 'Object',
              'optional': true,
              'doc': 'What it is currently set to.',
            },
            <String, Object?>{
              'name': 'default',
              'type': 'Object',
              'optional': true,
              'doc':
                  'What the demo renders with when nothing is set — also what it shows outside the catalog.',
            },
            <String, Object?>{
              'name': 'min',
              'type': 'num',
              'optional': true,
              'doc': 'Bounds, when the demo gave any.',
            },
            <String, Object?>{'name': 'max', 'type': 'num', 'optional': true},
            <String, Object?>{
              'name': 'options',
              'type': 'List<String>',
              'doc': 'A picker\'s labels, in declaration order.',
            },
          ],
        },
      },
    ],
  }),
  'CatalogEntrySummary': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogEntrySummary',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'id',
        'type': 'String',
        'doc': 'What `screenshot --entry` and `describe --entry` take.',
      },
      <String, Object?>{'name': 'name', 'type': 'String'},
      <String, Object?>{
        'name': 'address',
        'type': 'String',
        'doc':
            'The `Address`, rendered — hand it back to `screenshot`, or later `show`.',
      },
      <String, Object?>{
        'name': 'group',
        'type': 'String',
        'optional': true,
        'doc':
            'One tree level between the directory and the leaf, when the entry declares or derives one.',
      },
      <String, Object?>{
        'name': 'formFactor',
        'type': 'String',
        'optional': true,
        'doc':
            '`mobile`, `desktop`, `all` — what the demo says it is *for*, when it says.',
      },
    ],
  }),
  'CatalogKnob': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogKnob',
    'fields': <Object?>[
      <String, Object?>{'name': 'name', 'type': 'String'},
      <String, Object?>{
        'name': 'kind',
        'type': 'String',
        'doc': '`string`, `boolean`, `integer`, `number`, `picker`.',
      },
      <String, Object?>{
        'name': 'value',
        'type': 'Object',
        'optional': true,
        'doc': 'What it is currently set to.',
      },
      <String, Object?>{
        'name': 'default',
        'type': 'Object',
        'optional': true,
        'doc':
            'What the demo renders with when nothing is set — also what it shows outside the catalog.',
      },
      <String, Object?>{
        'name': 'min',
        'type': 'num',
        'optional': true,
        'doc': 'Bounds, when the demo gave any.',
      },
      <String, Object?>{'name': 'max', 'type': 'num', 'optional': true},
      <String, Object?>{
        'name': 'options',
        'type': 'List<String>',
        'doc': 'A picker\'s labels, in declaration order.',
      },
    ],
  }),
  'CatalogPackageCheck': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogPackageCheck',
    'fields': <Object?>[
      <String, Object?>{'name': 'path', 'type': 'String'},
      <String, Object?>{
        'name': 'ok',
        'type': 'bool',
        'doc': 'True when nothing is quarantined.',
      },
      <String, Object?>{
        'name': 'servable',
        'type': 'List<String>',
        'doc': 'Entry ids the compiler built.',
      },
      <String, Object?>{
        'name': 'broken',
        'type': 'List<CatalogBrokenEntry>',
        'shape': <String, Object?>{
          'type': 'CatalogBrokenEntry',
          'fields': <Object?>[
            <String, Object?>{'name': 'id', 'type': 'String'},
            <String, Object?>{
              'name': 'error',
              'type': 'String',
              'doc': 'The compiler\'s diagnostics, verbatim.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'error',
        'type': 'String',
        'optional': true,
        'doc':
            'Set when the daemon could not be reached at all, which is not the same as "everything failed to compile".',
      },
    ],
  }),
  'CatalogPackageEntries': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogPackageEntries',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'path',
        'type': 'String',
        'doc': 'Package path as declared in `tool/flutterware.dart`.',
      },
      <String, Object?>{
        'name': 'entries',
        'type': 'List<CatalogEntrySummary>',
        'shape': <String, Object?>{
          'type': 'CatalogEntrySummary',
          'fields': <Object?>[
            <String, Object?>{
              'name': 'id',
              'type': 'String',
              'doc': 'What `screenshot --entry` and `describe --entry` take.',
            },
            <String, Object?>{'name': 'name', 'type': 'String'},
            <String, Object?>{
              'name': 'address',
              'type': 'String',
              'doc':
                  'The `Address`, rendered — hand it back to `screenshot`, or later `show`.',
            },
            <String, Object?>{
              'name': 'group',
              'type': 'String',
              'optional': true,
              'doc':
                  'One tree level between the directory and the leaf, when the entry declares or derives one.',
            },
            <String, Object?>{
              'name': 'formFactor',
              'type': 'String',
              'optional': true,
              'doc':
                  '`mobile`, `desktop`, `all` — what the demo says it is *for*, when it says.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'diagnostics',
        'type': 'List<String>',
        'doc':
            'Discovery\'s complaints — a duplicate id, an uncallable target.',
      },
      <String, Object?>{
        'name': 'error',
        'type': 'String',
        'optional': true,
        'doc':
            'Set when the scan failed, in which case [entries] is empty and means nothing.',
      },
    ],
  }),
  'DependencyEntry': ResultShape.fromJson(<String, Object?>{
    'type': 'DependencyEntry',
    'fields': <Object?>[
      <String, Object?>{'name': 'name', 'type': 'String'},
      <String, Object?>{
        'name': 'direct',
        'type': 'bool',
        'doc':
            'Declared in this package\'s own pubspec, as opposed to pulled in by something else.',
      },
      <String, Object?>{
        'name': 'version',
        'type': 'String',
        'optional': true,
        'doc': 'Null for a package whose pubspec declares none.',
      },
      <String, Object?>{
        'name': 'source',
        'type': 'String',
        'optional': true,
        'doc': '`hosted`, `git`, `path` — where pub resolved it from.',
      },
    ],
  }),
  'DependencyListPackage': ResultShape.fromJson(<String, Object?>{
    'type': 'DependencyListPackage',
    'fields': <Object?>[
      <String, Object?>{'name': 'path', 'type': 'String'},
      <String, Object?>{
        'name': 'direct',
        'type': 'int',
        'doc':
            'Counts are always both, even when only the direct ones are listed: a list that silently dropped 156 packages and said nothing would read as "this package has 14 dependencies".',
      },
      <String, Object?>{'name': 'transitive', 'type': 'int'},
      <String, Object?>{
        'name': 'dependencies',
        'type': 'List<DependencyEntry>',
        'shape': <String, Object?>{
          'type': 'DependencyEntry',
          'fields': <Object?>[
            <String, Object?>{'name': 'name', 'type': 'String'},
            <String, Object?>{
              'name': 'direct',
              'type': 'bool',
              'doc':
                  'Declared in this package\'s own pubspec, as opposed to pulled in by something else.',
            },
            <String, Object?>{
              'name': 'version',
              'type': 'String',
              'optional': true,
              'doc': 'Null for a package whose pubspec declares none.',
            },
            <String, Object?>{
              'name': 'source',
              'type': 'String',
              'optional': true,
              'doc': '`hosted`, `git`, `path` — where pub resolved it from.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'error',
        'type': 'String',
        'optional': true,
        'doc':
            'Set when the package could not be loaded, in which case the counts mean nothing.',
      },
    ],
  }),
  'DependencyListResult': ResultShape.fromJson(<String, Object?>{
    'type': 'DependencyListResult',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'packages',
        'type': 'List<DependencyListPackage>',
        'shape': <String, Object?>{
          'type': 'DependencyListPackage',
          'fields': <Object?>[
            <String, Object?>{'name': 'path', 'type': 'String'},
            <String, Object?>{
              'name': 'direct',
              'type': 'int',
              'doc':
                  'Counts are always both, even when only the direct ones are listed: a list that silently dropped 156 packages and said nothing would read as "this package has 14 dependencies".',
            },
            <String, Object?>{'name': 'transitive', 'type': 'int'},
            <String, Object?>{
              'name': 'dependencies',
              'type': 'List<DependencyEntry>',
              'shape': <String, Object?>{
                'type': 'DependencyEntry',
                'fields': <Object?>[
                  <String, Object?>{'name': 'name', 'type': 'String'},
                  <String, Object?>{
                    'name': 'direct',
                    'type': 'bool',
                    'doc':
                        'Declared in this package\'s own pubspec, as opposed to pulled in by something else.',
                  },
                  <String, Object?>{
                    'name': 'version',
                    'type': 'String',
                    'optional': true,
                    'doc': 'Null for a package whose pubspec declares none.',
                  },
                  <String, Object?>{
                    'name': 'source',
                    'type': 'String',
                    'optional': true,
                    'doc':
                        '`hosted`, `git`, `path` — where pub resolved it from.',
                  },
                ],
              },
            },
            <String, Object?>{
              'name': 'error',
              'type': 'String',
              'optional': true,
              'doc':
                  'Set when the package could not be loaded, in which case the counts mean nothing.',
            },
          ],
        },
      },
    ],
  }),
};
