// GENERATED by tool/generate_capabilities.dart. Do not edit by hand.
//
// ignore_for_file: avoid_escaping_inner_quotes
//
// The wire shape of every action result, read out of the classes themselves.
// `test/session/action_shapes_test.dart` fails when this no longer matches the
// source, so editing it by hand only postpones the disagreement.

import 'package:flutterware/plugins.dart';

/// Result shapes by class name — look one up with `PluginAction.returnsName`.
final resultShapes = <String, ResultShape>{
  'AnimationFactsResult': ResultShape.fromJson(<String, Object?>{
    'type': 'AnimationFactsResult',
    'fields': <Object?>[
      <String, Object?>{'name': 'width', 'type': 'int'},
      <String, Object?>{'name': 'height', 'type': 'int'},
      <String, Object?>{'name': 'frameRate', 'type': 'double'},
      <String, Object?>{'name': 'frames', 'type': 'int'},
      <String, Object?>{'name': 'durationMs', 'type': 'int'},
      <String, Object?>{'name': 'version', 'type': 'String', 'optional': true},
      <String, Object?>{
        'name': 'layers',
        'type': 'List<AnimationLayerResult>',
        'doc': 'Outermost first, the order the document lists them.',
        'shape': <String, Object?>{
          'type': 'AnimationLayerResult',
          'fields': <Object?>[
            <String, Object?>{'name': 'name', 'type': 'String'},
            <String, Object?>{'name': 'type', 'type': 'String'},
          ],
        },
      },
      <String, Object?>{
        'name': 'markers',
        'type': 'List<String>',
        'doc':
            'Named points an exporter left behind — what a caller would seek to.',
      },
    ],
  }),
  'AnimationLayerResult': ResultShape.fromJson(<String, Object?>{
    'type': 'AnimationLayerResult',
    'fields': <Object?>[
      <String, Object?>{'name': 'name', 'type': 'String'},
      <String, Object?>{'name': 'type', 'type': 'String'},
    ],
  }),
  'Artifact': ResultShape.fromJson(<String, Object?>{
    'type': 'Artifact',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'kind',
        'type': 'String',
        'doc': 'A MIME type where one fits — see the constants above.',
      },
      <String, Object?>{
        'name': 'address',
        'type': 'String',
        'doc': 'What this is an artifact of, axes included.',
      },
      <String, Object?>{
        'name': 'path',
        'type': 'String',
        'optional': true,
        'doc': 'Where it was written, when it was written.',
      },
      <String, Object?>{
        'name': 'text',
        'type': 'String',
        'optional': true,
        'doc':
            'The content itself, for artifacts small enough that making the reader open a file is worse than carrying it.',
      },
      <String, Object?>{
        'name': 'meta',
        'type': 'Map<String, Object?>',
        'optional': true,
        'doc':
            'Anything the producer wants the reader to know: timings, compile stats, exit codes.',
      },
    ],
  }),
  'AssetAuditResult': ResultShape.fromJson(<String, Object?>{
    'type': 'AssetAuditResult',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'checked',
        'type': 'int',
        'doc':
            'How many keys were looked at — the denominator, so an empty findings list means "nothing wrong" rather than "nothing examined".',
      },
      <String, Object?>{
        'name': 'bytes',
        'type': 'int',
        'doc': 'Every byte in the audited bundles.',
      },
      <String, Object?>{
        'name': 'findings',
        'type': 'List<AssetFinding>',
        'doc': 'Only what is wrong.',
        'shape': <String, Object?>{
          'type': 'AssetFinding',
          'fields': <Object?>[
            <String, Object?>{
              'name': 'kind',
              'type': 'String',
              'doc':
                  'A stable slug, so a caller can filter without matching prose: `declared-missing`, `unreachable-file`, `density-gap`, `duplicate`, `oversized`, `over-budget`.',
            },
            <String, Object?>{
              'name': 'summary',
              'type': 'String',
              'doc': 'One line, for a human reading a list.',
            },
            <String, Object?>{
              'name': 'detail',
              'type': 'String',
              'doc':
                  'What was found, specifically — the sizes, the paths, the densities.',
            },
            <String, Object?>{
              'name': 'package',
              'type': 'String',
              'optional': true,
              'doc': 'The package whose bundle this is about.',
            },
            <String, Object?>{
              'name': 'key',
              'type': 'String',
              'optional': true,
              'doc': 'The asset key, where the finding is about one.',
            },
            <String, Object?>{
              'name': 'address',
              'type': 'String',
              'optional': true,
              'doc': 'Where to look, where there is somewhere.',
            },
            <String, Object?>{
              'name': 'path',
              'type': 'String',
              'optional': true,
              'doc':
                  'A path relative to the package, for findings about a file rather than a key.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'unreadable',
        'type': 'List<String>',
        'doc':
            'Packages that could not be scanned at all, which is not the same as a package with nothing wrong.',
      },
    ],
  }),
  'AssetDensity': ResultShape.fromJson(<String, Object?>{
    'type': 'AssetDensity',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'scale',
        'type': 'double',
        'optional': true,
        'doc':
            'Null for the main asset, which serves whatever no variant covers.',
      },
      <String, Object?>{'name': 'file', 'type': 'String'},
      <String, Object?>{'name': 'bytes', 'type': 'int'},
    ],
  }),
  'AssetDescription': ResultShape.fromJson(<String, Object?>{
    'type': 'AssetDescription',
    'fields': <Object?>[
      <String, Object?>{'name': 'key', 'type': 'String'},
      <String, Object?>{'name': 'kind', 'type': 'String'},
      <String, Object?>{'name': 'address', 'type': 'String'},
      <String, Object?>{
        'name': 'declaration',
        'type': 'String',
        'doc':
            'The pubspec entry that pulled it in — for a directory declaration this is the only answer to "why is this in my bundle".',
      },
      <String, Object?>{
        'name': 'file',
        'type': 'String',
        'doc': 'Where the main file is, relative to its package.',
      },
      <String, Object?>{
        'name': 'bytes',
        'type': 'int',
        'doc': 'The main file, and then every density together.',
      },
      <String, Object?>{'name': 'totalBytes', 'type': 'int'},
      <String, Object?>{
        'name': 'code',
        'type': 'String',
        'doc': 'The Dart that loads it.',
      },
      <String, Object?>{'name': 'package', 'type': 'String', 'optional': true},
      <String, Object?>{
        'name': 'densities',
        'type': 'List<AssetDensity>',
        'shape': <String, Object?>{
          'type': 'AssetDensity',
          'fields': <Object?>[
            <String, Object?>{
              'name': 'scale',
              'type': 'double',
              'optional': true,
              'doc':
                  'Null for the main asset, which serves whatever no variant covers.',
            },
            <String, Object?>{'name': 'file', 'type': 'String'},
            <String, Object?>{'name': 'bytes', 'type': 'int'},
          ],
        },
      },
      <String, Object?>{
        'name': 'raster',
        'type': 'RasterFactsResult',
        'optional': true,
        'doc': 'Present for a raster whose header could be read.',
        'shape': <String, Object?>{
          'type': 'RasterFactsResult',
          'fields': <Object?>[
            <String, Object?>{'name': 'width', 'type': 'int'},
            <String, Object?>{'name': 'height', 'type': 'int'},
            <String, Object?>{
              'name': 'frames',
              'type': 'int',
              'doc': 'Above one for an animated GIF or WebP.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'animation',
        'type': 'AnimationFactsResult',
        'optional': true,
        'doc': 'Present for a `.json` that turned out to be an animation.',
        'shape': <String, Object?>{
          'type': 'AnimationFactsResult',
          'fields': <Object?>[
            <String, Object?>{'name': 'width', 'type': 'int'},
            <String, Object?>{'name': 'height', 'type': 'int'},
            <String, Object?>{'name': 'frameRate', 'type': 'double'},
            <String, Object?>{'name': 'frames', 'type': 'int'},
            <String, Object?>{'name': 'durationMs', 'type': 'int'},
            <String, Object?>{
              'name': 'version',
              'type': 'String',
              'optional': true,
            },
            <String, Object?>{
              'name': 'layers',
              'type': 'List<AnimationLayerResult>',
              'doc': 'Outermost first, the order the document lists them.',
              'shape': <String, Object?>{
                'type': 'AnimationLayerResult',
                'fields': <Object?>[
                  <String, Object?>{'name': 'name', 'type': 'String'},
                  <String, Object?>{'name': 'type', 'type': 'String'},
                ],
              },
            },
            <String, Object?>{
              'name': 'markers',
              'type': 'List<String>',
              'doc':
                  'Named points an exporter left behind — what a caller would seek to.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'font',
        'type': 'FontFactsResult',
        'optional': true,
        'doc': 'Present for a file a `fonts:` entry named.',
        'shape': <String, Object?>{
          'type': 'FontFactsResult',
          'fields': <Object?>[
            <String, Object?>{
              'name': 'family',
              'type': 'String',
              'doc':
                  'The family the pubspec declared, package prefix included where there is one.',
            },
            <String, Object?>{
              'name': 'weight',
              'type': 'int',
              'optional': true,
              'doc': 'What the pubspec *claims*.',
            },
            <String, Object?>{
              'name': 'style',
              'type': 'String',
              'optional': true,
            },
          ],
        },
      },
    ],
  }),
  'AssetEntry': ResultShape.fromJson(<String, Object?>{
    'type': 'AssetEntry',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'key',
        'type': 'String',
        'doc': 'What `Image.asset` is given.',
      },
      <String, Object?>{'name': 'kind', 'type': 'String'},
      <String, Object?>{
        'name': 'bytes',
        'type': 'int',
        'doc': 'The asset and its density variants together.',
      },
      <String, Object?>{
        'name': 'address',
        'type': 'String',
        'doc':
            'Where it is, so a caller can act on it without a second lookup.',
      },
      <String, Object?>{
        'name': 'package',
        'type': 'String',
        'optional': true,
        'doc': 'The package that declared it; absent for the bundle\'s own.',
      },
      <String, Object?>{
        'name': 'densities',
        'type': 'List<double>',
        'doc': 'Which densities exist beside the main file — `[2.0, 3.0]`.',
      },
    ],
  }),
  'AssetFinding': ResultShape.fromJson(<String, Object?>{
    'type': 'AssetFinding',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'kind',
        'type': 'String',
        'doc':
            'A stable slug, so a caller can filter without matching prose: `declared-missing`, `unreachable-file`, `density-gap`, `duplicate`, `oversized`, `over-budget`.',
      },
      <String, Object?>{
        'name': 'summary',
        'type': 'String',
        'doc': 'One line, for a human reading a list.',
      },
      <String, Object?>{
        'name': 'detail',
        'type': 'String',
        'doc':
            'What was found, specifically — the sizes, the paths, the densities.',
      },
      <String, Object?>{
        'name': 'package',
        'type': 'String',
        'optional': true,
        'doc': 'The package whose bundle this is about.',
      },
      <String, Object?>{
        'name': 'key',
        'type': 'String',
        'optional': true,
        'doc': 'The asset key, where the finding is about one.',
      },
      <String, Object?>{
        'name': 'address',
        'type': 'String',
        'optional': true,
        'doc': 'Where to look, where there is somewhere.',
      },
      <String, Object?>{
        'name': 'path',
        'type': 'String',
        'optional': true,
        'doc':
            'A path relative to the package, for findings about a file rather than a key.',
      },
    ],
  }),
  'AssetListPackage': ResultShape.fromJson(<String, Object?>{
    'type': 'AssetListPackage',
    'fields': <Object?>[
      <String, Object?>{'name': 'path', 'type': 'String'},
      <String, Object?>{
        'name': 'own',
        'type': 'int',
        'doc':
            'Counts are always both, even when only the package\'s own assets are listed: a list that silently dropped 340 dependency assets would read as "this bundle has nine things in it".',
      },
      <String, Object?>{'name': 'fromPackages', 'type': 'int'},
      <String, Object?>{
        'name': 'bytes',
        'type': 'int',
        'doc':
            'Every byte in the bundle, dependencies included, whatever was listed.',
      },
      <String, Object?>{
        'name': 'assets',
        'type': 'List<AssetEntry>',
        'shape': <String, Object?>{
          'type': 'AssetEntry',
          'fields': <Object?>[
            <String, Object?>{
              'name': 'key',
              'type': 'String',
              'doc': 'What `Image.asset` is given.',
            },
            <String, Object?>{'name': 'kind', 'type': 'String'},
            <String, Object?>{
              'name': 'bytes',
              'type': 'int',
              'doc': 'The asset and its density variants together.',
            },
            <String, Object?>{
              'name': 'address',
              'type': 'String',
              'doc':
                  'Where it is, so a caller can act on it without a second lookup.',
            },
            <String, Object?>{
              'name': 'package',
              'type': 'String',
              'optional': true,
              'doc':
                  'The package that declared it; absent for the bundle\'s own.',
            },
            <String, Object?>{
              'name': 'densities',
              'type': 'List<double>',
              'doc':
                  'Which densities exist beside the main file — `[2.0, 3.0]`.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'error',
        'type': 'String',
        'optional': true,
        'doc':
            'Set when the package could not be scanned, in which case the counts mean nothing.',
      },
    ],
  }),
  'AssetListResult': ResultShape.fromJson(<String, Object?>{
    'type': 'AssetListResult',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'packages',
        'type': 'List<AssetListPackage>',
        'shape': <String, Object?>{
          'type': 'AssetListPackage',
          'fields': <Object?>[
            <String, Object?>{'name': 'path', 'type': 'String'},
            <String, Object?>{
              'name': 'own',
              'type': 'int',
              'doc':
                  'Counts are always both, even when only the package\'s own assets are listed: a list that silently dropped 340 dependency assets would read as "this bundle has nine things in it".',
            },
            <String, Object?>{'name': 'fromPackages', 'type': 'int'},
            <String, Object?>{
              'name': 'bytes',
              'type': 'int',
              'doc':
                  'Every byte in the bundle, dependencies included, whatever was listed.',
            },
            <String, Object?>{
              'name': 'assets',
              'type': 'List<AssetEntry>',
              'shape': <String, Object?>{
                'type': 'AssetEntry',
                'fields': <Object?>[
                  <String, Object?>{
                    'name': 'key',
                    'type': 'String',
                    'doc': 'What `Image.asset` is given.',
                  },
                  <String, Object?>{'name': 'kind', 'type': 'String'},
                  <String, Object?>{
                    'name': 'bytes',
                    'type': 'int',
                    'doc': 'The asset and its density variants together.',
                  },
                  <String, Object?>{
                    'name': 'address',
                    'type': 'String',
                    'doc':
                        'Where it is, so a caller can act on it without a second lookup.',
                  },
                  <String, Object?>{
                    'name': 'package',
                    'type': 'String',
                    'optional': true,
                    'doc':
                        'The package that declared it; absent for the bundle\'s own.',
                  },
                  <String, Object?>{
                    'name': 'densities',
                    'type': 'List<double>',
                    'doc':
                        'Which densities exist beside the main file — `[2.0, 3.0]`.',
                  },
                ],
              },
            },
            <String, Object?>{
              'name': 'error',
              'type': 'String',
              'optional': true,
              'doc':
                  'Set when the package could not be scanned, in which case the counts mean nothing.',
            },
          ],
        },
      },
    ],
  }),
  'CatalogAuditEntry': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogAuditEntry',
    'fields': <Object?>[
      <String, Object?>{'name': 'id', 'type': 'String'},
      <String, Object?>{'name': 'address', 'type': 'String'},
      <String, Object?>{
        'name': 'compiles',
        'type': 'bool',
        'doc': 'False when the compiler quarantined it.',
      },
      <String, Object?>{
        'name': 'compileError',
        'type': 'String',
        'optional': true,
        'doc': 'The compiler\'s diagnostics, verbatim.',
      },
      <String, Object?>{
        'name': 'errors',
        'type': 'List<CatalogRenderError>',
        'shape': <String, Object?>{
          'type': 'CatalogRenderError',
          'fields': <Object?>[
            <String, Object?>{'name': 'exception', 'type': 'String'},
            <String, Object?>{
              'name': 'library',
              'type': 'String',
              'optional': true,
              'doc':
                  '`widgets library`, `rendering library` — which tells a layout overflow from a failed image load without reading the message.',
            },
            <String, Object?>{
              'name': 'context',
              'type': 'String',
              'optional': true,
              'doc':
                  'What the framework was doing: `during layout`, `while painting`.',
            },
            <String, Object?>{
              'name': 'count',
              'type': 'int',
              'doc': 'How many times this exact error was reported.',
            },
          ],
        },
      },
    ],
  }),
  'CatalogAuditFailure': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogAuditFailure',
    'fields': <Object?>[
      <String, Object?>{'name': 'package', 'type': 'String'},
      <String, Object?>{'name': 'error', 'type': 'String'},
    ],
  }),
  'CatalogAuditResult': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogAuditResult',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'checked',
        'type': 'int',
        'doc': 'How many entries were looked at.',
      },
      <String, Object?>{
        'name': 'broken',
        'type': 'int',
        'doc':
            'How many of them are broken — the number the whole thing exists to produce, so that a caller has an answer before it has read a list.',
      },
      <String, Object?>{
        'name': 'entries',
        'type': 'List<CatalogAuditEntry>',
        'doc': 'Only the ones with something to say.',
        'shape': <String, Object?>{
          'type': 'CatalogAuditEntry',
          'fields': <Object?>[
            <String, Object?>{'name': 'id', 'type': 'String'},
            <String, Object?>{'name': 'address', 'type': 'String'},
            <String, Object?>{
              'name': 'compiles',
              'type': 'bool',
              'doc': 'False when the compiler quarantined it.',
            },
            <String, Object?>{
              'name': 'compileError',
              'type': 'String',
              'optional': true,
              'doc': 'The compiler\'s diagnostics, verbatim.',
            },
            <String, Object?>{
              'name': 'errors',
              'type': 'List<CatalogRenderError>',
              'shape': <String, Object?>{
                'type': 'CatalogRenderError',
                'fields': <Object?>[
                  <String, Object?>{'name': 'exception', 'type': 'String'},
                  <String, Object?>{
                    'name': 'library',
                    'type': 'String',
                    'optional': true,
                    'doc':
                        '`widgets library`, `rendering library` — which tells a layout overflow from a failed image load without reading the message.',
                  },
                  <String, Object?>{
                    'name': 'context',
                    'type': 'String',
                    'optional': true,
                    'doc':
                        'What the framework was doing: `during layout`, `while painting`.',
                  },
                  <String, Object?>{
                    'name': 'count',
                    'type': 'int',
                    'doc': 'How many times this exact error was reported.',
                  },
                ],
              },
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'unreachable',
        'type': 'List<CatalogAuditFailure>',
        'doc':
            'Packages that could not be audited at all, which is not the same as a package whose entries are fine.',
        'shape': <String, Object?>{
          'type': 'CatalogAuditFailure',
          'fields': <Object?>[
            <String, Object?>{'name': 'package', 'type': 'String'},
            <String, Object?>{'name': 'error', 'type': 'String'},
          ],
        },
      },
    ],
  }),
  'CatalogBrokenEntry': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogBrokenEntry',
    'fields': <Object?>[
      <String, Object?>{'name': 'id', 'type': 'String'},
      <String, Object?>{
        'name': 'error',
        'type': 'String',
        'doc': 'The compiler\'s diagnostics, verbatim.',
      },
    ],
  }),
  'CatalogCheckResult': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogCheckResult',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'packages',
        'type': 'List<CatalogPackageCheck>',
        'shape': <String, Object?>{
          'type': 'CatalogPackageCheck',
          'fields': <Object?>[
            <String, Object?>{'name': 'path', 'type': 'String'},
            <String, Object?>{
              'name': 'ok',
              'type': 'bool',
              'doc': 'True when nothing is quarantined.',
            },
            <String, Object?>{
              'name': 'servable',
              'type': 'List<String>',
              'doc': 'Entry ids the compiler built.',
            },
            <String, Object?>{
              'name': 'broken',
              'type': 'List<CatalogBrokenEntry>',
              'shape': <String, Object?>{
                'type': 'CatalogBrokenEntry',
                'fields': <Object?>[
                  <String, Object?>{'name': 'id', 'type': 'String'},
                  <String, Object?>{
                    'name': 'error',
                    'type': 'String',
                    'doc': 'The compiler\'s diagnostics, verbatim.',
                  },
                ],
              },
            },
            <String, Object?>{
              'name': 'error',
              'type': 'String',
              'optional': true,
              'doc':
                  'Set when the daemon could not be reached at all, which is not the same as "everything failed to compile".',
            },
          ],
        },
      },
    ],
  }),
  'CatalogEntriesResult': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogEntriesResult',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'packages',
        'type': 'List<CatalogPackageEntries>',
        'shape': <String, Object?>{
          'type': 'CatalogPackageEntries',
          'fields': <Object?>[
            <String, Object?>{
              'name': 'path',
              'type': 'String',
              'doc': 'Package path as declared in `tool/flutterware.dart`.',
            },
            <String, Object?>{
              'name': 'entries',
              'type': 'List<CatalogEntrySummary>',
              'shape': <String, Object?>{
                'type': 'CatalogEntrySummary',
                'fields': <Object?>[
                  <String, Object?>{
                    'name': 'id',
                    'type': 'String',
                    'doc':
                        'What `screenshot --entry` and `describe --entry` take.',
                  },
                  <String, Object?>{'name': 'name', 'type': 'String'},
                  <String, Object?>{
                    'name': 'address',
                    'type': 'String',
                    'doc':
                        'The `Address`, rendered — hand it back to `screenshot`, or later `show`.',
                  },
                  <String, Object?>{
                    'name': 'group',
                    'type': 'String',
                    'optional': true,
                    'doc':
                        'One tree level between the directory and the leaf, when the entry declares or derives one.',
                  },
                  <String, Object?>{
                    'name': 'formFactor',
                    'type': 'String',
                    'optional': true,
                    'doc':
                        '`mobile`, `desktop`, `all` — what the demo says it is *for*, when it says.',
                  },
                ],
              },
            },
            <String, Object?>{
              'name': 'diagnostics',
              'type': 'List<String>',
              'doc':
                  'Discovery\'s complaints — a duplicate id, an uncallable target.',
            },
            <String, Object?>{
              'name': 'error',
              'type': 'String',
              'optional': true,
              'doc':
                  'Set when the scan failed, in which case [entries] is empty and means nothing.',
            },
          ],
        },
      },
    ],
  }),
  'CatalogEntryDescription': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogEntryDescription',
    'fields': <Object?>[
      <String, Object?>{'name': 'id', 'type': 'String'},
      <String, Object?>{'name': 'name', 'type': 'String'},
      <String, Object?>{
        'name': 'package',
        'type': 'String',
        'doc': 'Which declared package holds it.',
      },
      <String, Object?>{
        'name': 'file',
        'type': 'String',
        'doc': 'Project-relative path of the declaring file.',
      },
      <String, Object?>{
        'name': 'symbol',
        'type': 'String',
        'doc': 'The annotated top-level function.',
      },
      <String, Object?>{
        'name': 'annotation',
        'type': 'String',
        'doc':
            'The annotation\'s source text, verbatim — `Demo(name: \'Counter\')`.',
      },
      <String, Object?>{'name': 'address', 'type': 'String'},
      <String, Object?>{'name': 'group', 'type': 'String', 'optional': true},
      <String, Object?>{
        'name': 'formFactor',
        'type': 'String',
        'optional': true,
      },
      <String, Object?>{
        'name': 'knobs',
        'type': 'List<CatalogKnob>',
        'optional': true,
        'doc':
            'Present only when `--knobs` asked for them: reading a knob costs a compile and a frame, so absent means "not looked at" while an empty list means "this entry declares none".',
        'shape': <String, Object?>{
          'type': 'CatalogKnob',
          'fields': <Object?>[
            <String, Object?>{'name': 'name', 'type': 'String'},
            <String, Object?>{
              'name': 'kind',
              'type': 'String',
              'doc': '`string`, `boolean`, `integer`, `number`, `picker`.',
            },
            <String, Object?>{
              'name': 'value',
              'type': 'Object',
              'optional': true,
              'doc': 'What it is currently set to.',
            },
            <String, Object?>{
              'name': 'default',
              'type': 'Object',
              'optional': true,
              'doc':
                  'What the demo renders with when nothing is set — also what it shows outside the catalog.',
            },
            <String, Object?>{
              'name': 'min',
              'type': 'num',
              'optional': true,
              'doc': 'Bounds, when the demo gave any.',
            },
            <String, Object?>{'name': 'max', 'type': 'num', 'optional': true},
            <String, Object?>{
              'name': 'options',
              'type': 'List<String>',
              'doc': 'A picker\'s labels, in declaration order.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'axes',
        'type': 'List<CatalogKnob>',
        'optional': true,
        'doc': 'What the shell around the entry offers — theme, locale.',
        'shape': <String, Object?>{
          'type': 'CatalogKnob',
          'fields': <Object?>[
            <String, Object?>{'name': 'name', 'type': 'String'},
            <String, Object?>{
              'name': 'kind',
              'type': 'String',
              'doc': '`string`, `boolean`, `integer`, `number`, `picker`.',
            },
            <String, Object?>{
              'name': 'value',
              'type': 'Object',
              'optional': true,
              'doc': 'What it is currently set to.',
            },
            <String, Object?>{
              'name': 'default',
              'type': 'Object',
              'optional': true,
              'doc':
                  'What the demo renders with when nothing is set — also what it shows outside the catalog.',
            },
            <String, Object?>{
              'name': 'min',
              'type': 'num',
              'optional': true,
              'doc': 'Bounds, when the demo gave any.',
            },
            <String, Object?>{'name': 'max', 'type': 'num', 'optional': true},
            <String, Object?>{
              'name': 'options',
              'type': 'List<String>',
              'doc': 'A picker\'s labels, in declaration order.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'shell',
        'type': 'String',
        'optional': true,
        'doc': 'Which shell declared [axes].',
      },
    ],
  }),
  'CatalogEntrySummary': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogEntrySummary',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'id',
        'type': 'String',
        'doc': 'What `screenshot --entry` and `describe --entry` take.',
      },
      <String, Object?>{'name': 'name', 'type': 'String'},
      <String, Object?>{
        'name': 'address',
        'type': 'String',
        'doc':
            'The `Address`, rendered — hand it back to `screenshot`, or later `show`.',
      },
      <String, Object?>{
        'name': 'group',
        'type': 'String',
        'optional': true,
        'doc':
            'One tree level between the directory and the leaf, when the entry declares or derives one.',
      },
      <String, Object?>{
        'name': 'formFactor',
        'type': 'String',
        'optional': true,
        'doc':
            '`mobile`, `desktop`, `all` — what the demo says it is *for*, when it says.',
      },
    ],
  }),
  'CatalogInspectResult': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogInspectResult',
    'fields': <Object?>[
      <String, Object?>{'name': 'entry', 'type': 'String'},
      <String, Object?>{'name': 'address', 'type': 'String'},
      <String, Object?>{
        'name': 'readFrom',
        'type': 'String',
        'doc':
            'Where this reading came from: `live` when it was taken from a session somebody has open — the demo in whatever state they left it, including anything they reached by clicking — and `render` when this call built and drew its own copy.',
      },
      <String, Object?>{
        'name': 'ok',
        'type': 'bool',
        'doc': 'Whether it rendered without the framework reporting anything.',
      },
      <String, Object?>{
        'name': 'errors',
        'type': 'List<CatalogRenderError>',
        'shape': <String, Object?>{
          'type': 'CatalogRenderError',
          'fields': <Object?>[
            <String, Object?>{'name': 'exception', 'type': 'String'},
            <String, Object?>{
              'name': 'library',
              'type': 'String',
              'optional': true,
              'doc':
                  '`widgets library`, `rendering library` — which tells a layout overflow from a failed image load without reading the message.',
            },
            <String, Object?>{
              'name': 'context',
              'type': 'String',
              'optional': true,
              'doc':
                  'What the framework was doing: `during layout`, `while painting`.',
            },
            <String, Object?>{
              'name': 'count',
              'type': 'int',
              'doc': 'How many times this exact error was reported.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'tree',
        'type': 'List<CatalogTreeNode>',
        'optional': true,
        'doc': 'The tree, when `--tree` asked for it.',
        'shape': <String, Object?>{
          'type': 'CatalogTreeNode',
          'fields': <Object?>[
            <String, Object?>{
              'name': 'id',
              'type': 'String',
              'doc':
                  'The child-index path from the demo\'s root — `\'\'`, `0`, `0/1`.',
            },
            <String, Object?>{
              'name': 'type',
              'type': 'String',
              'doc': 'The widget\'s runtime type.',
            },
            <String, Object?>{
              'name': 'depth',
              'type': 'int',
              'doc':
                  'How deep below the demo\'s root, so a flat list still reads as a tree.',
            },
            <String, Object?>{
              'name': 'description',
              'type': 'String',
              'optional': true,
              'doc':
                  'The framework\'s one-line description when it says more than [type] does — `Text("Save")` rather than `Text`.',
            },
            <String, Object?>{
              'name': 'source',
              'type': 'String',
              'optional': true,
              'doc': '`path/to/file.dart:12:5`, project-relative.',
            },
            <String, Object?>{
              'name': 'local',
              'type': 'bool',
              'doc':
                  'Whether the framework counts this as the user\'s code rather than `package:flutter`\'s.',
            },
            <String, Object?>{
              'name': 'rect',
              'type': 'String',
              'optional': true,
              'doc': 'Where it ended up: `x,y w×h`.',
            },
            <String, Object?>{
              'name': 'constraints',
              'type': 'String',
              'optional': true,
              'doc': 'What the parent allowed: `w 0.0..900.0, h 0.0..∞`.',
            },
            <String, Object?>{
              'name': 'flex',
              'type': 'String',
              'optional': true,
              'doc':
                  'For a `Row`, `Column` or `Flex`: `horizontal, start, center, max`.',
            },
            <String, Object?>{
              'name': 'flexChild',
              'type': 'String',
              'optional': true,
              'doc':
                  'For a *child* of one: `flex 2 (tight)`, read off the parent data.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'matches',
        'type': 'List<CatalogTreeNode>',
        'optional': true,
        'doc': 'The nodes matching `--find`.',
        'shape': <String, Object?>{
          'type': 'CatalogTreeNode',
          'fields': <Object?>[
            <String, Object?>{
              'name': 'id',
              'type': 'String',
              'doc':
                  'The child-index path from the demo\'s root — `\'\'`, `0`, `0/1`.',
            },
            <String, Object?>{
              'name': 'type',
              'type': 'String',
              'doc': 'The widget\'s runtime type.',
            },
            <String, Object?>{
              'name': 'depth',
              'type': 'int',
              'doc':
                  'How deep below the demo\'s root, so a flat list still reads as a tree.',
            },
            <String, Object?>{
              'name': 'description',
              'type': 'String',
              'optional': true,
              'doc':
                  'The framework\'s one-line description when it says more than [type] does — `Text("Save")` rather than `Text`.',
            },
            <String, Object?>{
              'name': 'source',
              'type': 'String',
              'optional': true,
              'doc': '`path/to/file.dart:12:5`, project-relative.',
            },
            <String, Object?>{
              'name': 'local',
              'type': 'bool',
              'doc':
                  'Whether the framework counts this as the user\'s code rather than `package:flutter`\'s.',
            },
            <String, Object?>{
              'name': 'rect',
              'type': 'String',
              'optional': true,
              'doc': 'Where it ended up: `x,y w×h`.',
            },
            <String, Object?>{
              'name': 'constraints',
              'type': 'String',
              'optional': true,
              'doc': 'What the parent allowed: `w 0.0..900.0, h 0.0..∞`.',
            },
            <String, Object?>{
              'name': 'flex',
              'type': 'String',
              'optional': true,
              'doc':
                  'For a `Row`, `Column` or `Flex`: `horizontal, start, center, max`.',
            },
            <String, Object?>{
              'name': 'flexChild',
              'type': 'String',
              'optional': true,
              'doc':
                  'For a *child* of one: `flex 2 (tight)`, read off the parent data.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'at',
        'type': 'List<CatalogTreeNode>',
        'optional': true,
        'doc':
            'The chain under `--at`, outermost first — the thing under a cursor is usually a `Text` and the thing meant is the button around it.',
        'shape': <String, Object?>{
          'type': 'CatalogTreeNode',
          'fields': <Object?>[
            <String, Object?>{
              'name': 'id',
              'type': 'String',
              'doc':
                  'The child-index path from the demo\'s root — `\'\'`, `0`, `0/1`.',
            },
            <String, Object?>{
              'name': 'type',
              'type': 'String',
              'doc': 'The widget\'s runtime type.',
            },
            <String, Object?>{
              'name': 'depth',
              'type': 'int',
              'doc':
                  'How deep below the demo\'s root, so a flat list still reads as a tree.',
            },
            <String, Object?>{
              'name': 'description',
              'type': 'String',
              'optional': true,
              'doc':
                  'The framework\'s one-line description when it says more than [type] does — `Text("Save")` rather than `Text`.',
            },
            <String, Object?>{
              'name': 'source',
              'type': 'String',
              'optional': true,
              'doc': '`path/to/file.dart:12:5`, project-relative.',
            },
            <String, Object?>{
              'name': 'local',
              'type': 'bool',
              'doc':
                  'Whether the framework counts this as the user\'s code rather than `package:flutter`\'s.',
            },
            <String, Object?>{
              'name': 'rect',
              'type': 'String',
              'optional': true,
              'doc': 'Where it ended up: `x,y w×h`.',
            },
            <String, Object?>{
              'name': 'constraints',
              'type': 'String',
              'optional': true,
              'doc': 'What the parent allowed: `w 0.0..900.0, h 0.0..∞`.',
            },
            <String, Object?>{
              'name': 'flex',
              'type': 'String',
              'optional': true,
              'doc':
                  'For a `Row`, `Column` or `Flex`: `horizontal, start, center, max`.',
            },
            <String, Object?>{
              'name': 'flexChild',
              'type': 'String',
              'optional': true,
              'doc':
                  'For a *child* of one: `flex 2 (tight)`, read off the parent data.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'logs',
        'type': 'List<String>',
        'optional': true,
        'doc': 'What the demo printed, when `--logs` asked.',
      },
      <String, Object?>{
        'name': 'logsDropped',
        'type': 'int',
        'optional': true,
        'doc':
            'How many earlier lines fell off the guest\'s buffer, when any did.',
      },
      <String, Object?>{
        'name': 'screenshot',
        'type': 'Artifact',
        'optional': true,
        'doc': 'The picture, when `--screenshot` asked for one.',
        'shape': <String, Object?>{
          'type': 'Artifact',
          'fields': <Object?>[
            <String, Object?>{
              'name': 'kind',
              'type': 'String',
              'doc': 'A MIME type where one fits — see the constants above.',
            },
            <String, Object?>{
              'name': 'address',
              'type': 'String',
              'doc': 'What this is an artifact of, axes included.',
            },
            <String, Object?>{
              'name': 'path',
              'type': 'String',
              'optional': true,
              'doc': 'Where it was written, when it was written.',
            },
            <String, Object?>{
              'name': 'text',
              'type': 'String',
              'optional': true,
              'doc':
                  'The content itself, for artifacts small enough that making the reader open a file is worse than carrying it.',
            },
            <String, Object?>{
              'name': 'meta',
              'type': 'Map<String, Object?>',
              'optional': true,
              'doc':
                  'Anything the producer wants the reader to know: timings, compile stats, exit codes.',
            },
          ],
        },
      },
    ],
  }),
  'CatalogKnob': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogKnob',
    'fields': <Object?>[
      <String, Object?>{'name': 'name', 'type': 'String'},
      <String, Object?>{
        'name': 'kind',
        'type': 'String',
        'doc': '`string`, `boolean`, `integer`, `number`, `picker`.',
      },
      <String, Object?>{
        'name': 'value',
        'type': 'Object',
        'optional': true,
        'doc': 'What it is currently set to.',
      },
      <String, Object?>{
        'name': 'default',
        'type': 'Object',
        'optional': true,
        'doc':
            'What the demo renders with when nothing is set — also what it shows outside the catalog.',
      },
      <String, Object?>{
        'name': 'min',
        'type': 'num',
        'optional': true,
        'doc': 'Bounds, when the demo gave any.',
      },
      <String, Object?>{'name': 'max', 'type': 'num', 'optional': true},
      <String, Object?>{
        'name': 'options',
        'type': 'List<String>',
        'doc': 'A picker\'s labels, in declaration order.',
      },
    ],
  }),
  'CatalogPackageCheck': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogPackageCheck',
    'fields': <Object?>[
      <String, Object?>{'name': 'path', 'type': 'String'},
      <String, Object?>{
        'name': 'ok',
        'type': 'bool',
        'doc': 'True when nothing is quarantined.',
      },
      <String, Object?>{
        'name': 'servable',
        'type': 'List<String>',
        'doc': 'Entry ids the compiler built.',
      },
      <String, Object?>{
        'name': 'broken',
        'type': 'List<CatalogBrokenEntry>',
        'shape': <String, Object?>{
          'type': 'CatalogBrokenEntry',
          'fields': <Object?>[
            <String, Object?>{'name': 'id', 'type': 'String'},
            <String, Object?>{
              'name': 'error',
              'type': 'String',
              'doc': 'The compiler\'s diagnostics, verbatim.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'error',
        'type': 'String',
        'optional': true,
        'doc':
            'Set when the daemon could not be reached at all, which is not the same as "everything failed to compile".',
      },
    ],
  }),
  'CatalogPackageEntries': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogPackageEntries',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'path',
        'type': 'String',
        'doc': 'Package path as declared in `tool/flutterware.dart`.',
      },
      <String, Object?>{
        'name': 'entries',
        'type': 'List<CatalogEntrySummary>',
        'shape': <String, Object?>{
          'type': 'CatalogEntrySummary',
          'fields': <Object?>[
            <String, Object?>{
              'name': 'id',
              'type': 'String',
              'doc': 'What `screenshot --entry` and `describe --entry` take.',
            },
            <String, Object?>{'name': 'name', 'type': 'String'},
            <String, Object?>{
              'name': 'address',
              'type': 'String',
              'doc':
                  'The `Address`, rendered — hand it back to `screenshot`, or later `show`.',
            },
            <String, Object?>{
              'name': 'group',
              'type': 'String',
              'optional': true,
              'doc':
                  'One tree level between the directory and the leaf, when the entry declares or derives one.',
            },
            <String, Object?>{
              'name': 'formFactor',
              'type': 'String',
              'optional': true,
              'doc':
                  '`mobile`, `desktop`, `all` — what the demo says it is *for*, when it says.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'diagnostics',
        'type': 'List<String>',
        'doc':
            'Discovery\'s complaints — a duplicate id, an uncallable target.',
      },
      <String, Object?>{
        'name': 'error',
        'type': 'String',
        'optional': true,
        'doc':
            'Set when the scan failed, in which case [entries] is empty and means nothing.',
      },
    ],
  }),
  'CatalogRenderError': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogRenderError',
    'fields': <Object?>[
      <String, Object?>{'name': 'exception', 'type': 'String'},
      <String, Object?>{
        'name': 'library',
        'type': 'String',
        'optional': true,
        'doc':
            '`widgets library`, `rendering library` — which tells a layout overflow from a failed image load without reading the message.',
      },
      <String, Object?>{
        'name': 'context',
        'type': 'String',
        'optional': true,
        'doc':
            'What the framework was doing: `during layout`, `while painting`.',
      },
      <String, Object?>{
        'name': 'count',
        'type': 'int',
        'doc': 'How many times this exact error was reported.',
      },
    ],
  }),
  'CatalogTreeNode': ResultShape.fromJson(<String, Object?>{
    'type': 'CatalogTreeNode',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'id',
        'type': 'String',
        'doc':
            'The child-index path from the demo\'s root — `\'\'`, `0`, `0/1`.',
      },
      <String, Object?>{
        'name': 'type',
        'type': 'String',
        'doc': 'The widget\'s runtime type.',
      },
      <String, Object?>{
        'name': 'depth',
        'type': 'int',
        'doc':
            'How deep below the demo\'s root, so a flat list still reads as a tree.',
      },
      <String, Object?>{
        'name': 'description',
        'type': 'String',
        'optional': true,
        'doc':
            'The framework\'s one-line description when it says more than [type] does — `Text("Save")` rather than `Text`.',
      },
      <String, Object?>{
        'name': 'source',
        'type': 'String',
        'optional': true,
        'doc': '`path/to/file.dart:12:5`, project-relative.',
      },
      <String, Object?>{
        'name': 'local',
        'type': 'bool',
        'doc':
            'Whether the framework counts this as the user\'s code rather than `package:flutter`\'s.',
      },
      <String, Object?>{
        'name': 'rect',
        'type': 'String',
        'optional': true,
        'doc': 'Where it ended up: `x,y w×h`.',
      },
      <String, Object?>{
        'name': 'constraints',
        'type': 'String',
        'optional': true,
        'doc': 'What the parent allowed: `w 0.0..900.0, h 0.0..∞`.',
      },
      <String, Object?>{
        'name': 'flex',
        'type': 'String',
        'optional': true,
        'doc':
            'For a `Row`, `Column` or `Flex`: `horizontal, start, center, max`.',
      },
      <String, Object?>{
        'name': 'flexChild',
        'type': 'String',
        'optional': true,
        'doc':
            'For a *child* of one: `flex 2 (tight)`, read off the parent data.',
      },
    ],
  }),
  'DependencyEntry': ResultShape.fromJson(<String, Object?>{
    'type': 'DependencyEntry',
    'fields': <Object?>[
      <String, Object?>{'name': 'name', 'type': 'String'},
      <String, Object?>{
        'name': 'direct',
        'type': 'bool',
        'doc':
            'Declared in this package\'s own pubspec, as opposed to pulled in by something else.',
      },
      <String, Object?>{
        'name': 'dev',
        'type': 'bool',
        'doc': 'Declared in `dev_dependencies:` rather than `dependencies:`.',
      },
      <String, Object?>{
        'name': 'version',
        'type': 'String',
        'optional': true,
        'doc': 'The resolved version — what is on disk.',
      },
      <String, Object?>{
        'name': 'constraint',
        'type': 'String',
        'optional': true,
        'doc': 'The constraint the depending package wrote — `^1.2.0`, `any`.',
      },
      <String, Object?>{
        'name': 'source',
        'type': 'String',
        'doc':
            '`hosted`, `git`, `path`, `sdk`, `root` — where pub resolved it from.',
      },
      <String, Object?>{
        'name': 'origin',
        'type': 'String',
        'optional': true,
        'doc':
            'The identifying detail behind [source]: the git repository and ref, the relative path, a non-pub.dev server.',
      },
    ],
  }),
  'DependencyListPackage': ResultShape.fromJson(<String, Object?>{
    'type': 'DependencyListPackage',
    'fields': <Object?>[
      <String, Object?>{'name': 'path', 'type': 'String'},
      <String, Object?>{
        'name': 'direct',
        'type': 'int',
        'doc':
            'Counts are always all three, even when only the declared ones are listed: a list that silently dropped 156 packages and said nothing would read as "this package has 14 dependencies".',
      },
      <String, Object?>{'name': 'dev', 'type': 'int'},
      <String, Object?>{'name': 'transitive', 'type': 'int'},
      <String, Object?>{
        'name': 'dependencies',
        'type': 'List<DependencyEntry>',
        'shape': <String, Object?>{
          'type': 'DependencyEntry',
          'fields': <Object?>[
            <String, Object?>{'name': 'name', 'type': 'String'},
            <String, Object?>{
              'name': 'direct',
              'type': 'bool',
              'doc':
                  'Declared in this package\'s own pubspec, as opposed to pulled in by something else.',
            },
            <String, Object?>{
              'name': 'dev',
              'type': 'bool',
              'doc':
                  'Declared in `dev_dependencies:` rather than `dependencies:`.',
            },
            <String, Object?>{
              'name': 'version',
              'type': 'String',
              'optional': true,
              'doc': 'The resolved version — what is on disk.',
            },
            <String, Object?>{
              'name': 'constraint',
              'type': 'String',
              'optional': true,
              'doc':
                  'The constraint the depending package wrote — `^1.2.0`, `any`.',
            },
            <String, Object?>{
              'name': 'source',
              'type': 'String',
              'doc':
                  '`hosted`, `git`, `path`, `sdk`, `root` — where pub resolved it from.',
            },
            <String, Object?>{
              'name': 'origin',
              'type': 'String',
              'optional': true,
              'doc':
                  'The identifying detail behind [source]: the git repository and ref, the relative path, a non-pub.dev server.',
            },
          ],
        },
      },
      <String, Object?>{
        'name': 'error',
        'type': 'String',
        'optional': true,
        'doc':
            'Set when the package could not be loaded, in which case the counts mean nothing.',
      },
    ],
  }),
  'DependencyListResult': ResultShape.fromJson(<String, Object?>{
    'type': 'DependencyListResult',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'packages',
        'type': 'List<DependencyListPackage>',
        'shape': <String, Object?>{
          'type': 'DependencyListPackage',
          'fields': <Object?>[
            <String, Object?>{'name': 'path', 'type': 'String'},
            <String, Object?>{
              'name': 'direct',
              'type': 'int',
              'doc':
                  'Counts are always all three, even when only the declared ones are listed: a list that silently dropped 156 packages and said nothing would read as "this package has 14 dependencies".',
            },
            <String, Object?>{'name': 'dev', 'type': 'int'},
            <String, Object?>{'name': 'transitive', 'type': 'int'},
            <String, Object?>{
              'name': 'dependencies',
              'type': 'List<DependencyEntry>',
              'shape': <String, Object?>{
                'type': 'DependencyEntry',
                'fields': <Object?>[
                  <String, Object?>{'name': 'name', 'type': 'String'},
                  <String, Object?>{
                    'name': 'direct',
                    'type': 'bool',
                    'doc':
                        'Declared in this package\'s own pubspec, as opposed to pulled in by something else.',
                  },
                  <String, Object?>{
                    'name': 'dev',
                    'type': 'bool',
                    'doc':
                        'Declared in `dev_dependencies:` rather than `dependencies:`.',
                  },
                  <String, Object?>{
                    'name': 'version',
                    'type': 'String',
                    'optional': true,
                    'doc': 'The resolved version — what is on disk.',
                  },
                  <String, Object?>{
                    'name': 'constraint',
                    'type': 'String',
                    'optional': true,
                    'doc':
                        'The constraint the depending package wrote — `^1.2.0`, `any`.',
                  },
                  <String, Object?>{
                    'name': 'source',
                    'type': 'String',
                    'doc':
                        '`hosted`, `git`, `path`, `sdk`, `root` — where pub resolved it from.',
                  },
                  <String, Object?>{
                    'name': 'origin',
                    'type': 'String',
                    'optional': true,
                    'doc':
                        'The identifying detail behind [source]: the git repository and ref, the relative path, a non-pub.dev server.',
                  },
                ],
              },
            },
            <String, Object?>{
              'name': 'error',
              'type': 'String',
              'optional': true,
              'doc':
                  'Set when the package could not be loaded, in which case the counts mean nothing.',
            },
          ],
        },
      },
    ],
  }),
  'FontFactsResult': ResultShape.fromJson(<String, Object?>{
    'type': 'FontFactsResult',
    'fields': <Object?>[
      <String, Object?>{
        'name': 'family',
        'type': 'String',
        'doc':
            'The family the pubspec declared, package prefix included where there is one.',
      },
      <String, Object?>{
        'name': 'weight',
        'type': 'int',
        'optional': true,
        'doc': 'What the pubspec *claims*.',
      },
      <String, Object?>{'name': 'style', 'type': 'String', 'optional': true},
    ],
  }),
  'RasterFactsResult': ResultShape.fromJson(<String, Object?>{
    'type': 'RasterFactsResult',
    'fields': <Object?>[
      <String, Object?>{'name': 'width', 'type': 'int'},
      <String, Object?>{'name': 'height', 'type': 'int'},
      <String, Object?>{
        'name': 'frames',
        'type': 'int',
        'doc': 'Above one for an animated GIF or WebP.',
      },
    ],
  }),
};
