import 'package:flutterware/plugins.dart';

// ignore: implementation_imports
import 'package:flutterware/src/log_client.dart';

import '../context.dart';
import '../plugins/plugin_core.dart';
import '../shell/workspace.dart';
import '../shell/worktree.dart';
import '../utils/flutter_sdk.dart';
import 'action_shapes.generated.dart';
import 'cli.dart';
import 'mcp_server.dart';
import 'session.dart';

/// Renders what this build can do, as markdown.
///
/// Written to `docs/capabilities.md` by `tool/generate_capabilities.dart` and
/// checked by `test/tools/capabilities_test.dart`, so the document is a
/// consequence of the code rather than a description of it that someone has to
/// remember to update.
///
/// **Schema, not data.** It resolves the cores against a synthetic one-package
/// project, so what comes out is the shape every project gets — the actions and
/// their parameters — and not this repo's entry ids or dependency names. Those
/// belong to `fw run … entries` and `fw run … list`, which is rather the point:
/// a capability document that listed the data would be describing one project.
String renderCapabilities({
  PluginCoreRegistry? registry,
  Map<String, ResultShape>? shapes,
}) {
  var cores = _resolve(registry ?? defaultCoreRegistry());
  var sections = [
    _header,
    _cliSection(),
    _mcpSection(),
    _actionsSection(cores, shapes ?? resultShapes),
  ];
  return '${sections.map((section) => section.trim()).join('\n\n')}\n';
}

/// The plugin ids this build knows, resolved against a project that declares
/// all of them and one package.
List<PluginCore> _resolve(PluginCoreRegistry registry) {
  const worktree = Worktree(path: '/project');
  var workspace = Workspace(
    root: worktree.path,
    declared: const [Pkg('.')],
    discovered: const ['.'],
    appContext: AppContext(logger: LogClient.print()),
    flutterSdk: FlutterSdkPath('/flutter'),
  );
  var manifest = PluginManifest([
    for (var id in registry.ids)
      PluginDeclaration(
        id: id,
        label: id.split('.').last,
        config: const {
          'packages': [
            {'path': '.'},
          ],
        },
      ),
  ]);
  return Session.resolved(
    worktree: worktree,
    workspace: workspace,
    manifest: manifest,
    registry: registry,
  ).cores;
}

const _header = '''
<!-- Generated by app/tool/generate_capabilities.dart. Do not edit by hand. -->

# What flutterware can do

Every capability below is reachable from all three surfaces, because all three
drive the same `PluginCore`s through the same `Session.invoke`. The GUI adds a
panel; it does not add abilities.

Regenerate with:

```sh
cd app && dart run tool/generate_capabilities.dart
```
''';

/// The CLI, rendered from `fwCommands` — the same list `fw help` prints.
///
/// It used to be prose here *and* prose in `FwCli`, which is two copies of a
/// command summary and one drift away from a document describing a flag that
/// no longer exists.
String _cliSection() {
  var buffer = StringBuffer('''
## `fw`

```sh
cd app && dart run bin/fw.dart <command>
```

| command | what it does |
|---|---|
''');
  for (var command in fwCommands) {
    buffer.writeln('| `${command.usage}` | ${command.summary} |');
  }
  buffer.writeln();
  buffer.writeln('$fwHelpFooter\n');
  buffer.writeln('Exit codes:\n');
  for (var code in fwExitCodes.entries) {
    buffer.writeln('- `${code.key}` — ${code.value}');
  }
  return buffer.toString();
}

String _mcpSection() {
  var buffer = StringBuffer('''
## MCP

```sh
cd app && dart run bin/mcp.dart
```

Stdout belongs to the protocol — anything said to a human goes to stderr.

''');
  for (var tool in FlutterwareMcpServer.tools) {
    buffer.writeln('### `${tool.name}`');
    buffer.writeln();
    buffer.writeln(tool.description ?? '');
    buffer.writeln();
    var properties = tool.inputSchema.properties ?? const {};
    if (properties.isEmpty) {
      buffer.writeln('Takes no arguments.');
      buffer.writeln();
      continue;
    }
    var required = tool.inputSchema.required ?? const [];
    buffer.writeln('| argument | required | |');
    buffer.writeln('|---|---|---|');
    for (var entry in properties.entries) {
      var description = (entry.value as Map<String, Object?>)['description'];
      buffer.writeln(
        '| `${entry.key}` | ${required.contains(entry.key) ? 'yes' : 'no'} '
        '| ${_cell(description as String?)} |',
      );
    }
    buffer.writeln();
  }
  return buffer.toString();
}

String _actionsSection(
  List<PluginCore> cores,
  Map<String, ResultShape> shapes,
) {
  var buffer = StringBuffer('## Plugins\n');
  for (var core in cores) {
    var report = core.report;
    buffer.writeln();
    buffer.writeln('### `${report.id}`');
    buffer.writeln();
    if (report.actions.isEmpty) {
      buffer.writeln('No actions.');
      continue;
    }
    var short = report.id.split('.').last;
    for (var action in report.actions) {
      buffer.writeln('#### `${action.id}` — ${action.label}');
      buffer.writeln();
      if (action.description != null) {
        buffer.writeln('${action.description}\n');
      }
      buffer.writeln('```sh');
      buffer.writeln(FwCli.usageLine(short, action));
      buffer.writeln('```');
      buffer.writeln();
      if (action.returnsName case var returns?) {
        buffer.writeln('Returns `$returns`:\n');
        if (shapes[returns] case var shape?) {
          buffer.writeln('```');
          buffer.write(shape.toText());
          buffer.writeln('```');
        } else {
          // Its `toJson` is hand-written, so its fields are not its keys and
          // nothing here can honestly claim to know them.
          buffer.writeln(
            'Shape not published: `$returns` writes its own `toJson`, so its '
            'fields are not its keys.',
          );
        }
        buffer.writeln();
      }
      if (action.parameters.isEmpty) {
        buffer.writeln('Takes no parameters.');
        buffer.writeln();
        continue;
      }
      buffer.writeln('| parameter | kind | required | default | |');
      buffer.writeln('|---|---|---|---|---|');
      for (var parameter in action.parameters) {
        buffer.writeln(
          '| `${parameter.id}` | ${_kind(parameter)} '
          '| ${parameter.required ? 'yes' : 'no'} '
          '| ${_cell(parameter.defaultValue)} '
          '| ${_cell(parameter.description)} |',
        );
      }
      buffer.writeln();
    }
  }
  return buffer.toString();
}

/// Where a `choice` gets its legal values, since the values themselves are
/// project data and change per project.
String _kind(ActionParameter parameter) {
  if (parameter.kind != ActionParameterKind.choice) return parameter.kind.name;
  if (parameter.optionsFrom case var from?) return 'choice (from `$from`)';
  return 'choice';
}

String _cell(String? value) =>
    value == null || value.isEmpty ? '—' : value.replaceAll('|', r'\|');
