// GENERATED by the flutterware scene editor. Do not edit.
//
// One arguments class per widget the app declares and per scene class
// beside it, so a scene file and a motion can name arguments with types
// instead of strings. Regenerated whenever a declaration or a scene's
// parameters change; every edit here is lost on the next save.

import 'package:flutterware/scene_authoring.dart';

import 'sample.scene.dart';
import 'sample_nested.scene.dart';
import 'scene_externals.dart';

class SampleChipArgs extends SceneExtArgs {
  const SampleChipArgs({this.label = 'chip', this.weight});

  final String label;
  final double? weight;

  @override
  String get entry => 'SampleChip';

  @override
  SampleChipArgs merge(SceneArgs fx) => SampleChipArgs(
    label: fx.text('label') ?? label,
    weight: fx.number('weight') ?? weight,
  );

  @override
  Map<String, Object?> toMap() => {'label': label, 'weight': ?weight};

  @override
  Object build() => _external('SampleChip').build(SceneArgs(toMap()));
}

class SampleChipTracks extends SceneExtTracks {
  const SampleChipTracks({this.weight});

  final MotionTrack? weight;

  @override
  Map<String, MotionTrack> toMap() => {'weight': ?weight};
}

class SampleBadgeArgs extends SceneRefArgs {
  const SampleBadgeArgs({
    this.label = 'New',
    this.tokens = const SceneTokens(),
  });

  final String label;
  final SceneTokens tokens;

  @override
  String get entry => 'SampleBadge';

  @override
  SampleBadgeArgs merge(SceneArgs fx) =>
      SampleBadgeArgs(label: fx.text('label') ?? label, tokens: tokens);

  @override
  Map<String, Object?> toMap() => {'label': label};

  @override
  SceneDefinition build() => SampleBadge(label: label, tokens: tokens);
}

class SampleBadgeTracks extends SceneExtTracks {
  const SampleBadgeTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class SampleSceneArgs extends SceneRefArgs {
  const SampleSceneArgs({
    this.headline = 'Fresh coffee, faster',
    this.tint = const SceneColor(0xFFE8632B),
    this.tokens = const SceneTokens(),
  });

  final String headline;
  final SceneColor tint;
  final SceneTokens tokens;

  @override
  String get entry => 'SampleScene';

  @override
  SampleSceneArgs merge(SceneArgs fx) => SampleSceneArgs(
    headline: fx.text('headline') ?? headline,
    tint: fx.color('tint') ?? tint,
    tokens: tokens,
  );

  @override
  Map<String, Object?> toMap() => {'headline': headline, 'tint': tint};

  @override
  SceneDefinition build() =>
      SampleScene(headline: headline, tint: tint, tokens: tokens);
}

class SampleSceneTracks extends SceneExtTracks {
  const SampleSceneTracks({this.tint});

  final MotionTrack? tint;

  @override
  Map<String, MotionTrack> toMap() => {'tint': ?tint};
}

/// The tokens `scene_tokens.dart` declares, typed. A scene
/// reads them through its tokens formal — `fill: tokens.brand`;
/// the bare constructor is the declared set.
class SceneTokens {
  const SceneTokens({
    this.surface = const SceneColor(0xFF2B1B12),
    this.ink = const SceneColor(0xFFFFFFFF),
  });

  final SceneColor surface;
  final SceneColor ink;

  static const dark = SceneTokens(
    surface: SceneColor(0xFF111111),
    ink: SceneColor(0xFFEEEEEE),
  );

  /// Every mode the declaration names, by name.
  static const modes = <String, SceneTokens>{'dark': dark};
}

/// The declaration an arguments class was generated from —
/// how a node builds itself, and why a shipped app hands
/// the view nothing.
ExternalWidget _external(String entry) =>
    sceneExternals.firstWhere((w) => w.entry == entry);
