// GENERATED by the flutterware scene editor. Do not edit.
//
// One arguments class per widget the app declares and per scene class
// beside it, so a scene file and a motion can name arguments with types
// instead of strings. Regenerated whenever a declaration or a scene's
// parameters change; every edit here is lost on the next save.

import 'package:flutterware/scene_authoring.dart';

import 'sample.scene.dart';
import 'sample_nested.scene.dart';
import 'scene_externals.dart';

class SampleChipArgs extends SceneExtArgs {
  const SampleChipArgs({this.label = 'chip', this.weight});

  final String label;
  final double? weight;

  @override
  String get entry => 'SampleChip';

  @override
  SampleChipArgs merge(SceneArgs fx) => SampleChipArgs(
    label: fx.text('label') ?? label,
    weight: fx.number('weight') ?? weight,
  );

  @override
  Map<String, Object?> toMap() => {'label': label, 'weight': ?weight};

  @override
  Object build() => _external('SampleChip').build(SceneArgs(toMap()));
}

class SampleChipTracks extends SceneExtTracks {
  const SampleChipTracks({this.weight});

  final MotionTrack? weight;

  @override
  Map<String, MotionTrack> toMap() => {'weight': ?weight};
}

class SampleBadgeArgs extends SceneRefArgs {
  const SampleBadgeArgs({this.label = 'New'});

  final String label;

  @override
  String get entry => 'SampleBadge';

  @override
  SampleBadgeArgs merge(SceneArgs fx) =>
      SampleBadgeArgs(label: fx.text('label') ?? label);

  @override
  Map<String, Object?> toMap() => {'label': label};

  @override
  SceneDefinition build() => SampleBadge(label: label);
}

class SampleBadgeTracks extends SceneExtTracks {
  const SampleBadgeTracks();

  @override
  Map<String, MotionTrack> toMap() => {};
}

class SampleSceneArgs extends SceneRefArgs {
  const SampleSceneArgs({
    this.headline = 'Fresh coffee, faster',
    this.tint = const SceneColor(0xFFE8632B),
  });

  final String headline;
  final SceneColor tint;

  @override
  String get entry => 'SampleScene';

  @override
  SampleSceneArgs merge(SceneArgs fx) => SampleSceneArgs(
    headline: fx.text('headline') ?? headline,
    tint: fx.color('tint') ?? tint,
  );

  @override
  Map<String, Object?> toMap() => {'headline': headline, 'tint': tint};

  @override
  SceneDefinition build() => SampleScene(headline: headline, tint: tint);
}

class SampleSceneTracks extends SceneExtTracks {
  const SampleSceneTracks({this.tint});

  final MotionTrack? tint;

  @override
  Map<String, MotionTrack> toMap() => {'tint': ?tint};
}

/// The declaration an arguments class was generated from —
/// how a node builds itself, and why a shipped app hands
/// the view nothing.
ExternalWidget _external(String entry) =>
    sceneExternals.firstWhere((w) => w.entry == entry);
