import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:flutterware/plugins.dart';
import 'package:flutterware_app/src/session/capabilities.dart';
import 'package:flutterware_app/src/session/shape_extractor.dart';
import 'package:path/path.dart' as p;

/// Writes what this build can do: the result shapes, then the document.
///
/// ```sh
/// cd app && dart run tool/generate_capabilities.dart
/// ```
///
/// Two outputs and they are not alternatives. [shapesPath] is Dart data read at
/// run time by the MCP server and by the document renderer — the analyzer runs
/// here and never on a request path. [capabilitiesPath] is the document.
///
/// Two tests keep them honest: one fails when the document no longer matches
/// the build (cheap), and one re-runs the extraction and fails when the shapes
/// no longer match the source (a few seconds). Between them there is no way to
/// change a result class and have the published shape stay wrong.
Future<void> main() async {
  var extracted = await ShapeExtractor(
    packageRoots: [for (var root in shapeRoots) p.absolute(root)],
  ).extract([for (var source in shapeSources) p.absolute(source)]);

  File(shapesPath)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(renderShapes(extracted));
  stdout.writeln('Wrote $shapesPath (${extracted.length} shapes)');

  File(capabilitiesPath)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(renderCapabilities(shapes: extracted));
  stdout.writeln('Wrote $capabilitiesPath');
}

/// The packages the sources below live in. Resolution needs whole packages.
///
/// Two of them because the result classes are not all in one: the plugins
/// declare most, and `Artifact` — the most returned of all — lives in
/// `package:flutterware` beside the other pure-data plugin types.
///
/// Named here rather than at the call site so the freshness test resolves the
/// same thing the generator did. A test that re-derives from a *different*
/// input is not a freshness test.
const shapeRoots = ['lib', '../lib'];

/// Where actions are declared. Resolution needs the package, but only these
/// files are scanned for `PluginAction(..., returns: …)`.
List<String> get shapeSources => [
  // Every core, found rather than listed. A hand-maintained list is a step a
  // new plugin can forget, and forgetting it does not fail: the document says
  // "Shape not published", which reads as a decision instead of an omission —
  // which is exactly what the asset plugin's three actions did on the day they
  // landed.
  //
  // Sorted, so the generated file does not shuffle with the filesystem.
  ...(Directory('lib/src/plugins/native')
      .listSync()
      .whereType<File>()
      .map((file) => file.path)
      .where((path) => path.endsWith('_core.dart'))
      .toList()
    ..sort()),
  // Not for its actions — it declares none — but for its hand-written
  // `toJson`, which is read as the shape of every artifact any action returns.
  '../lib/src/plugins/artifact.dart',
  // Same reason: the run report moved into the published package (a consumer
  // script reads `run.json` through it), and its hand-written `toJson`s are
  // what the `run` action's shape is read from.
  '../lib/src/scenarios/report.dart',
];

/// Relative to the `app/` package, which is where the generator and both tests
/// run from.
const capabilitiesPath = '../docs/capabilities.md';
const shapesPath = 'lib/src/session/action_shapes.generated.dart';

/// The shapes, as a Dart source file.
///
/// Emitted as `fromJson` over a literal rather than as constructor calls: the
/// map is data, and data with one shape is easier to keep correct than data
/// with a hand-rolled emitter per class.
String renderShapes(Map<String, ResultShape> shapes) {
  // Formatted here, not left to `prepare_submit`. Otherwise the formatter
  // rewrites the file after the generator wrote it, and the freshness test —
  // which compares the file to this function's output — fails forever on a
  // difference nobody made.
  return DartFormatter(
    languageVersion: DartFormatter.latestLanguageVersion,
  ).format(_renderShapes(shapes));
}

String _renderShapes(Map<String, ResultShape> shapes) {
  var buffer = StringBuffer('''
// GENERATED by tool/generate_capabilities.dart. Do not edit by hand.
//
// ignore_for_file: avoid_escaping_inner_quotes
//
// The wire shape of every action result, read out of the classes themselves.
// `test/session/action_shapes_test.dart` fails when this no longer matches the
// source, so editing it by hand only postpones the disagreement.

import 'package:flutterware/plugins.dart';

/// Result shapes by class name — look one up with `PluginAction.returnsName`.
final resultShapes = <String, ResultShape>{
''');
  for (var name in shapes.keys.toList()..sort()) {
    buffer.writeln("  '$name': ResultShape.fromJson(");
    buffer.writeln('    ${_literal(shapes[name]!.toJson(), '    ')},');
    buffer.writeln('  ),');
  }
  buffer.writeln('};');
  return buffer.toString();
}

/// A JSON value as Dart source. Not `jsonEncode`: the output is read by people
/// reviewing a diff, and one key per line is what makes a diff mean something.
String _literal(Object? value, String indent) {
  var inner = '$indent  ';
  return switch (value) {
    Map<String, Object?> map when map.isEmpty => '<String, Object?>{}',
    Map<String, Object?> map => [
      '<String, Object?>{',
      for (var entry in map.entries)
        "$inner'${entry.key}': ${_literal(entry.value, inner)},",
      '$indent}',
    ].join('\n'),
    List<Object?> list when list.isEmpty => '<Object?>[]',
    List<Object?> list => [
      '<Object?>[',
      for (var item in list) '$inner${_literal(item, inner)},',
      '$indent]',
    ].join('\n'),
    String text => "'${text.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'",
    _ => '$value',
  };
}
