import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';
import 'package:flutter_web_plugins/url_strategy.dart';
import 'package:web/web.dart' as web;

import '../previews/inline_guest.dart';
import '../shell/shell_view.dart';
import 'recorded_project.dart';
import 'recording.dart';

export '../previews/inline_guest.dart' show InlinePreviews;

/// The studio in a browser, over a recording.
///
/// The same shell the desktop app runs, opened on the recorded project rather
/// than on a checkout — see `src/demo/recorded_project.dart`. Nothing here
/// runs a process, reads a disk or opens a socket: git is a canned listing,
/// the manifest is built in-process, and the one plugin with a recording
/// behind it fetches that recording from `demo/fixture/` beside the page.
/// Everything else says it is not recorded, which is the truth and reads
/// better than a broken panel.
///
/// The previews are not recorded: [previews] is a table of the example's
/// entries compiled into the page, generated by `tool/demo/web_entries.dart`,
/// and the panel draws them as widgets of this very program.
///
/// This is the page the README links to: what the studio looks like, without
/// installing anything. `web_demo/demo/main.dart` is the entry point — its
/// own package, where both this one and the example's entries can be
/// imported — and `tool/demo/build_web.dart` builds it with the
/// recording copied beside it, which is what
/// `integration_test/web_demo_test.dart` opens in a real browser.
void runWebDemo({InlinePreviews? previews}) {
  // The same reason the export viewer gives: the engine's default strategy
  // rewrites the URL at boot, and this page has nowhere it wants to go.
  setUrlStrategy(null);
  WidgetsFlutterBinding.ensureInitialized();
  // Semantics on from the first frame, not behind the "enable accessibility"
  // placeholder the engine draws otherwise. It is what a screen reader gets,
  // and it is the only DOM a browser test can find a tab by: the page is
  // one canvas without it.
  _semantics = SemanticsBinding.instance.ensureSemantics();
  // Relative to the document's `<base href>`, which is what `--base-href`
  // wrote and what every other relative URL on the page resolves against —
  // where `Uri.base` is the address bar, and an address typed without its
  // trailing slash would resolve one directory up.
  var recording = HttpScenarioArtifacts(
    Uri.parse(web.document.baseURI).resolve('demo/fixture/'),
  );
  // The page's own title; the index this is built into is the example's.
  web.document.title = 'flutterware';
  var shell = recordedShell(recording: recording, previews: previews);
  runApp(ShellApp(shell));
  unawaited(shell.start(recordedProjectRoot));
}

/// Held for the life of the page; disposing it would turn semantics back off.
// ignore: unused_element
SemanticsHandle? _semantics;
