// GENERATED by tool/demo/web_entries.dart — do not edit.
// ignore_for_file: implementation_imports
//
// The previews the web demo shows — the coffee shop, a screen
// at a time — with a wrapper per entry beside this file.
import 'package:flutterware/previews_guest.dart';
import 'package:flutterware_app/src/previews/catalog_entry.dart';
import 'package:flutterware_app/src/previews/inline_guest.dart';

import 'entries/entry_0.dart' as e0;
import 'entries/entry_1.dart' as e1;
import 'entries/entry_2.dart' as e2;
import 'entries/entry_3.dart' as e3;
import 'entries/entry_4.dart' as e4;
import 'entries/entry_5.dart' as e5;
import 'entries/entry_6.dart' as e6;

const webDemoEntries = <CatalogEntry>[
  CatalogEntry(
    path: 'demo/brand.dart',
    symbol: 'appIcon',
    annotation: "Preview(name: 'App icon', group: 'Brewline')",
    name: 'App icon',
    group: 'Brewline',
    line: 12,
    endLine: 13,
  ),
  CatalogEntry(
    path: 'demo/shop.dart',
    symbol: 'shopBadges',
    annotation:
        "Preview(name: 'Drink badges', group: 'Brewline', wrapper: wrapInShop)",
    name: 'Drink badges',
    group: 'Brewline',
    line: 53,
    endLine: 54,
  ),
  CatalogEntry(
    path: 'demo/shop.dart',
    symbol: 'shopWelcome',
    annotation:
        "Preview(name: 'Welcome', group: 'Brewline', wrapper: wrapInShop)",
    name: 'Welcome',
    group: 'Brewline',
    line: 31,
    endLine: 32,
  ),
  CatalogEntry(
    path: 'demo/shop.dart',
    symbol: 'shopMenu',
    annotation: "Preview(name: 'Menu', group: 'Brewline', wrapper: wrapInShop)",
    name: 'Menu',
    group: 'Brewline',
    line: 34,
    endLine: 35,
  ),
  CatalogEntry(
    path: 'demo/shop.dart',
    symbol: 'shopDrink',
    annotation:
        "Preview(name: 'A drink', group: 'Brewline', wrapper: wrapInShop)",
    name: 'A drink',
    group: 'Brewline',
    line: 37,
    endLine: 38,
  ),
  CatalogEntry(
    path: 'demo/shop.dart',
    symbol: 'shopCart',
    annotation: "Preview(name: 'Cart', group: 'Brewline', wrapper: wrapInShop)",
    name: 'Cart',
    group: 'Brewline',
    line: 40,
    endLine: 41,
  ),
  CatalogEntry(
    path: 'demo/shop.dart',
    symbol: 'shopConfirmation',
    annotation:
        "Preview(name: 'Order placed', group: 'Brewline', wrapper: wrapInShop)",
    name: 'Order placed',
    group: 'Brewline',
    line: 43,
    endLine: 47,
  ),
];

CatalogEntryBuilder? webDemoEntryOf(String id) => switch (id) {
  'demo/brand.dart#appIcon' => (preview: e0.fwPreview, builder: e0.fwBuilder),
  'demo/shop.dart#shopBadges' => (preview: e1.fwPreview, builder: e1.fwBuilder),
  'demo/shop.dart#shopWelcome' => (
    preview: e2.fwPreview,
    builder: e2.fwBuilder,
  ),
  'demo/shop.dart#shopMenu' => (preview: e3.fwPreview, builder: e3.fwBuilder),
  'demo/shop.dart#shopDrink' => (preview: e4.fwPreview, builder: e4.fwBuilder),
  'demo/shop.dart#shopCart' => (preview: e5.fwPreview, builder: e5.fwBuilder),
  'demo/shop.dart#shopConfirmation' => (
    preview: e6.fwPreview,
    builder: e6.fwBuilder,
  ),
  _ => null,
};

InlinePreviews get webDemoPreviews =>
    (entries: webDemoEntries, entryOf: webDemoEntryOf);
