// GENERATED by tool/demo/web_entries.dart — do not edit.
// ignore_for_file: implementation_imports
//
// The previews of this example a browser can draw, with a wrapper per
// entry beside this file. Left out, with why:
//   demo/axes_preview.dart#variableAxes — demo/axes_preview.dart imports package:flutterware/scene.dart
//   demo/fox_probe.dart#foxProbe — lib/model_view.dart imports package:flutter_scene/scene.dart
//   demo/gpu_smoke.dart#gpuSmoke — demo/gpu_smoke.dart imports package:flutter_gpu/gpu.dart
//   demo/model_probe.dart#modelProbe — demo/model_probe.dart imports package:flutter_scene/scene.dart
//   demo/model_probe.dart#modelProbeBlender — demo/model_probe.dart imports package:flutter_scene/scene.dart
//   demo/model_probe.dart#modelProbeBuilt — demo/model_probe.dart imports package:flutter_scene/scene.dart
//   demo/phone_rig_probe.dart#phoneRigProbe — demo/phone_rig_probe.dart imports package:flutter_scene/scene.dart
//   demo/poster_preview.dart#arcadePoster — demo/poster_preview.dart imports package:flutterware/scene.dart
//   demo/poster_preview.dart#arcadePosterBreathing — demo/poster_preview.dart imports package:flutterware/scene.dart
//   demo/poster_preview.dart#arcadePosterWin — demo/poster_preview.dart imports package:flutterware/scene.dart
//   demo/runs_preview.dart#richRuns — demo/runs_preview.dart imports package:flutterware/scene.dart
//   demo/scene_args.dart#sceneCanvasHost — demo/scene_args.dart imports package:flutterware/scene_authoring.dart
//   demo/scene_args.dart#scenePlayer — demo/scene_args.dart imports package:flutterware/scene_authoring.dart
//   demo/store_hero_preview.dart#storeHero — demo/store_hero_preview.dart imports package:flutterware/scene.dart
//   demo/store_hero_preview.dart#storeHeroReveal — demo/store_hero_preview.dart imports package:flutterware/scene.dart
//   demo/store_panorama.dart#coffeeAppStore — lib/src/store_copy.dart imports dart:io
//   demo/store_panorama.dart#coffeeListing — lib/src/store_copy.dart imports dart:io
//   demo/store_panorama.dart#coffeeOne — lib/src/store_copy.dart imports dart:io
import 'package:flutterware/previews_guest.dart';
import 'package:flutterware_app/src/previews/catalog_entry.dart';
import 'package:flutterware_app/src/previews/inline_guest.dart';

import 'entries/entry_0.dart' as e0;
import 'entries/entry_1.dart' as e1;
import 'entries/entry_2.dart' as e2;
import 'entries/entry_3.dart' as e3;
import 'entries/entry_4.dart' as e4;
import 'entries/entry_5.dart' as e5;
import 'entries/entry_6.dart' as e6;
import 'entries/entry_7.dart' as e7;
import 'entries/entry_8.dart' as e8;

const webDemoEntries = <CatalogEntry>[
  CatalogEntry(
    path: 'demo/asset_smoke.dart',
    symbol: 'assetSmoke',
    annotation: "Preview(name: 'Asset smoke', wrapper: wrapInApp)",
    name: 'Asset smoke',
    line: 15,
    endLine: 40,
  ),
  CatalogEntry(
    path: 'demo/buttons.dart',
    symbol: 'buttons',
    annotation: "Preview(name: 'Buttons', wrapper: wrapInApp)",
    name: 'Buttons',
    line: 8,
    endLine: 25,
  ),
  CatalogEntry(
    path: 'demo/compute_probe.dart',
    symbol: 'computeProbe',
    annotation: "Preview(name: 'Compute probe', wrapper: wrapInApp)",
    name: 'Compute probe',
    line: 14,
    endLine: 15,
  ),
  CatalogEntry(
    path: 'demo/home_page.dart',
    symbol: 'homePageDefault',
    annotation:
        "Preview(name: 'Default', group: 'Home page', wrapper: wrapInApp)",
    name: 'Default',
    group: 'Home page',
    line: 10,
    endLine: 11,
  ),
  CatalogEntry(
    path: 'demo/home_page.dart',
    symbol: 'homePageMobile',
    annotation:
        "Preview(name: 'On a phone', group: 'Home page', wrapper: wrapInApp)",
    name: 'On a phone',
    group: 'Home page',
    line: 15,
    endLine: 16,
  ),
  CatalogEntry(
    path: 'demo/input.dart',
    symbol: 'keyboards',
    annotation:
        "Preview(name: 'Keyboards', group: 'Input', wrapper: wrapInApp)",
    name: 'Keyboards',
    group: 'Input',
    line: 20,
    endLine: 27,
  ),
  CatalogEntry(
    path: 'demo/input.dart',
    symbol: 'scrolling',
    annotation:
        "Preview(name: 'Scrolling', group: 'Input', wrapper: wrapInApp)",
    name: 'Scrolling',
    group: 'Input',
    line: 191,
    endLine: 202,
  ),
  CatalogEntry(
    path: 'demo/input.dart',
    symbol: 'textFields',
    annotation:
        "Preview(name: 'Text fields', group: 'Input', wrapper: wrapInApp)",
    name: 'Text fields',
    group: 'Input',
    line: 115,
    endLine: 139,
  ),
  CatalogEntry(
    path: 'demo/vector_smoke.dart',
    symbol: 'vectorSmoke',
    annotation: "Preview(name: 'Vector smoke', wrapper: wrapInApp)",
    name: 'Vector smoke',
    line: 14,
    endLine: 25,
  ),
];

CatalogEntryBuilder? webDemoEntryOf(String id) => switch (id) {
  'demo/asset_smoke.dart#assetSmoke' => (
    preview: e0.fwPreview,
    builder: e0.fwBuilder,
  ),
  'demo/buttons.dart#buttons' => (preview: e1.fwPreview, builder: e1.fwBuilder),
  'demo/compute_probe.dart#computeProbe' => (
    preview: e2.fwPreview,
    builder: e2.fwBuilder,
  ),
  'demo/home_page.dart#homePageDefault' => (
    preview: e3.fwPreview,
    builder: e3.fwBuilder,
  ),
  'demo/home_page.dart#homePageMobile' => (
    preview: e4.fwPreview,
    builder: e4.fwBuilder,
  ),
  'demo/input.dart#keyboards' => (preview: e5.fwPreview, builder: e5.fwBuilder),
  'demo/input.dart#scrolling' => (preview: e6.fwPreview, builder: e6.fwBuilder),
  'demo/input.dart#textFields' => (
    preview: e7.fwPreview,
    builder: e7.fwBuilder,
  ),
  'demo/vector_smoke.dart#vectorSmoke' => (
    preview: e8.fwPreview,
    builder: e8.fwBuilder,
  ),
  _ => null,
};

InlinePreviews get webDemoPreviews =>
    (entries: webDemoEntries, entryOf: webDemoEntryOf);
