// The studio is `publish_to: none` and has no public library; its demo is
// reached the way its own catalog demos reach it.
// ignore: implementation_imports
import 'package:flutterware_app/src/demo/web_demo.dart';

import 'entries.g.dart';

/// The studio's web demo: the shell over a recording of the example, with
/// the example's previews compiled in. See `web_demo.dart` in the app for
/// what runs; `entries.g.dart` beside this file is generated by
/// `app/tool/demo/web_entries.dart` and lists the entries a browser can draw.
/// Outside `lib/`, because the wrappers beside it reach the example's
/// previews by relative path.
void main() => runWebDemo(previews: webDemoPreviews);
