// The studio is `publish_to: none` and has no public library; its demo is
// reached the way its own catalog demos reach it.
// ignore: implementation_imports
import 'package:flutterware_app/src/demo/web_demo.dart';
import 'package:brewline/shop/shop_strings.dart';

import 'entries.g.dart';

/// The studio's web demo: the shell over a recording of the demo app, with
/// the demo app's previews compiled in. See `web_demo.dart` in the app for
/// what runs; `entries.g.dart` beside this file is generated by
/// `app/tool/demo/web_entries.dart` and lists the entries a browser can draw.
/// Outside `lib/`, because the wrappers beside it reach the demo app's
/// previews by relative path.
void main() {
  // The shop's strings are the demo app's assets, bundled here under its
  // package name.
  ShopStrings.assetPackage = 'brewline';
  runWebDemo(previews: webDemoPreviews);
}
